bigskysoftware/htmx

- www/examples.md
- www/examples/infinite-scroll.md
Here is where I am so far, but the `revealed` trigger does not seem to work properly, it just works for the first element. When I fallback on a classical click trigger, it works
Another thing, I found an inconsistency on `afterend`  (in the code) and `afterEnd` (in the doc)
Which one is the good one?
Thanks
> Infinite Scroll example with table of agents

- TODO.md
- src/kutty.js
- www/css/site.scss
- www/talk.md
The prompt variable inside issueAjaxRequest shadowed the prompt function
that it was attempting to use, thereby breaking the use of kt-prompt.
> Avoid shadowing the global prompt function

- www/css/site.scss
- www/examples.md
- www/examples/delete-row.md
- www/examples/infinite-scroll.md
- www/js/demo.js
I added a bit of code to support the DELETE requests, but it seem to fail working with the swap option:
the kutty-swapping class is added, but the element is never swapped with the content "" (empty, to delete the row)
Is it because it is empty?
> Example delete row

- www/docs.md
Typo: `hx-push` should be `hx-push-url`.
> Fix `hx-push-url` attribute

- www/docs.md
Typo: `hx-history-element` should be `hx-history-elt`.
> Fix `hx-history-elt` attribute.

- www/extensions.md
https://github.com/bigskysoftware/htmx/issues/49
> Make note of syntax for using multiple extensions

- README.md
> Uniform badges in README

- src/htmx.js
- test/attributes/hx-push-url.js
- www/attributes/hx-push-url.md
Re: https://github.com/bigskysoftware/htmx/issues/121
Tried my hand at writing a test this time ;)
> Allowed `hx-push-url` to accept a string

- www/posts/2020-6-30-htmx-0.0.7-is-released.md
- www/reference.md
PR'ing this to master because 0.0.7 is out.
> Added hx-vars to the docs and 0.0.7 release announcement

- dist/htmx.js
- src/htmx.js
FIXED CHROME issue - refuse to get unsafe header warning.
otherwise you will have to send explicitly header from server.
see LINE: 1500
I have`t updated dist/min.* Require to compile those, after merge.
> FIXED CHROME issue - "refuse to get unsafe header" warning.

- src/htmx.js
- test/index.html
- test/manual/scroll-test-eventHandler.html
- test/manual/scroll-test-startEnd.html
[As requested](https://github.com/bigskysoftware/htmx/issues/168#issuecomment-685244091), I'm moving this into its own PR.  
My apologies for the lack of tests.  I'm still trying to get my head around the testing tools that HTMX uses.  This did pass all of my manual tests.  In case it's helpful, I've posted my test page here: http://sseplaceholder.openfollow.org/scroll.html
> FIX: Scroll Event Throttling

- www/attributes/hx-sse.md
This documents the current state of the SSE PR #194.  I know we're still discussing updates to the syntax, and this will be updated if that changes.
Please let me know if this is too much or too little for the descriptions.  I tried to mirror the existing documentation style, but (obviously) feel free to make changes so that everything matches.
> DOCUMENTATION: Server Sent Events

- test/core/ajax.js
Added a test `child script nodes evaluate when first child` to confirm https://github.com/bigskysoftware/htmx/issues/228.
> Added test for script nodes

- src/htmx.js
- test/index.html
- test/manual/aborting-request.html
This is a fix for the issue I raised in #224.  
I'm new to this code base so this is very much WIP, but I've added what I think addresses the main problem and welcome any feedback.
> End request lock when xmlHttpRequest is aborted

- src/htmx.js
- test/core/ajax.js
> handle multi-select when "multiple" attr is present w/o value

- www/examples.md
- www/examples/tabs-hateoas.md
- www/examples/tabs-hyperscript.md
This PR answers #258 by showing two different ways to make tabs using htmx.
I am still having trouble getting the SASS stylesheet to compile correctly on my Mac, so I cannot see the final product with 100% fidelity.  If there are any problems with the way this PR renders (related to the stylesheet, or otherwise) please let me know and I will make corrections.
> Example Code for Tabs

- package.json
- www/examples.md
- www/examples/modal-custom.md
This adds one more modal dialog example -- using custom CSS that is not a part of any framework.
> More Documentation for Modal Dialogs

- www/reference.md
It took me a wile to find the matching part in the docs how to increase the duration of the settle and swap phase.
I hope this helps other newcomers.
> Link to hx-swap for timing (docs only).

- src/htmx.js
- test/core/validation.js
Hi @1cg here is the previous pull request but pulled into dev with tests as you requested.  Shout out if you have any more queries.
> skip validation when novalidate or form submitted indirectly

- www/attributes/hx-delete.md
- www/attributes/hx-get.md
- www/attributes/hx-patch.md
- www/attributes/hx-post.md
- www/attributes/hx-put.md
> Add note about data of hx-post

- www/events.md
Documented the `htmx:pushedIntoHistory` event
> Documented the htmx:pushedIntoHistory event

- www/reference.md
Added a link in the events list for the newly documented `htmx:pushedIntoHistory` event
> Added reference link to htmx:pushedIntoHistory event

- www/docs.md
Fix for a typo in the docs regarding SSE.
> Fixed typo in example for sse

- www/attributes/hx-delete.md
- www/attributes/hx-patch.md
- www/attributes/hx-put.md
- www/reference.md
Untrue since 2305aed18e925da55f15dc5798db37ac0142f2b4.
> Remove notes about X-HTTP-Method-Override

- src/ext/morphdom-swap.js
- test/ext/morphdom-swap.js
- www/extensions/morphdom-swap.md
> Handle DocumentFragement in morphdom-swap properly

- www/examples/modal-custom.md
Update modal example to use new wait for <eventName> syntax
> Update Modal Example

- www/docs.md
I had a hard time discovering this, I went straight to 'animations' instead, I think this would be helpful to have on the index. If you disagree, feel free to close with malice. =D
> add css transitions anchor to docs

- www/_includes/demo_ui.html.liquid
Otherwise you might not immediately understand that you can show the examples.
> Add style="cursor: pointer"

- src/htmx.js
> Trigger historyRestored after history actually has been restored

- www/api.md
Fixes various spelling / example syntax errors.
> Documentation updates

- .gitignore
- www/examples.md
- www/server-examples.md
List of GitHub repos showing a wide variety of server-side language demos of htmx.
> List of server-side language examples

- www/server-examples.md
Fix typo at start. Add bullets to make list easier to read.
> Fix typo at start. Add bullets to make list easier to read.

- src/ext/event-header.js
> Use one-line format for Triggering-Event header

- README.md
> Add doc section on npm

- src/ext/preload.js
Fixed bad formatting on [data-hx-get] selector
> Bugfix: Improper selector format

- www/examples/update-other-content.md
> Fix typo for oob in update other content example

- www/attributes/hx-prompt.md
> Fixed a typo in hx-prompt docs

- www/talk.md
> Updated link for .Net Rocks

- www/examples/progress-bar.md
> Fix typo in progress bar example

- www/extensions/path-deps.md
Just a tiny fix to avoid having two periods at the end of the sentence.
> www/extensions/path-deps: rm extra punctuation

- src/htmx.js
See #718
The test suite still pass.
> Make eventListener work on elements inside shadow DOM

- src/htmx.js
- test/attributes/hx-swap-oob.js
- test/attributes/hx-swap.js
- www/attributes/hx-swap.md
See #645 for motivation.
This is my first contribution, so let me know if this is incorrect or missing some other case.
> Add delete option for hx-swap

- www/docs.md
> Added webpack installation to docs

- src/htmx.js
- test/core/events.js
- www/events.md
- www/reference.md
> adding events around oob swaps

- www/js/demo/it.js
Demo code:
```html
<form hx-post="/form?token=123" hx-target="#result">
<input name="name" value="John Smith" />
<select name="role">
<option selected value="admin">Admin</option>
<option selected value="author">Author</option>
<option selected value="guest">Guest</option>
</select>
<button type="submit">Submit</button> 
</form>
<output id="result"></output>
<template url="/form">
<div>${JSON.stringify(params)}</div>
</template>
```
> Make posted data available to template tag.

- www/attributes/hx-swap.md
> Document outerHTML limitation on <body>

- package.json
- src/ext/loading-states.js
- test/ext/loading-states.js
- test/index.html
- www/extensions/loading-states.md
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-busy
Also add tests for the extension
> Add data-loading-aria-busy directive for loading-states extension

- www/essays/hypermedia-apis-vs-data-apis.md
Replace two instaces of `contant` for `contact`
> Fix typo in hypermedia-apis-vs-data-apis.md

- www/attributes/hx-push-url.md
- www/headers/hx-push.md
Expand descriptions, remove duplicate information on HX-Push, and add relevant links to MDN and `hx-history-elt`.
> Improve HX-Push and hx-push-url documentation

- www/examples/tabs-hyperscript.md
One sentence ended like this..
> Remove double period

- src/ext/disable-element.js
- test/ext/disable-element.js
- test/index.html
- www/extensions.md
- www/extensions/disable-element.md
Credits for the idea and the feature code go to @alexsemerad, the author of [the original PR](https://github.com/bigskysoftware/htmx/pull/812) for this extension. Mine is just adding tests and documentation.
> feat(ext): add disable-element extension

- src/htmx.js
> Check for localStorage availability

- www/events.md
- www/reference.md
Undocumented event tripped me up and a new guy in the discord.
> Added missing documentation: htmx:timeout event

- www/_includes/layout.njk
- www/css/site.scss
- www/docs.md
First of all thank you for this great project!
Second of all, this is just a suggestion. If you see anything valuable in this PR, that's great. But if you don't, just reject it and I won't try to discuss it too much. :)
I'm reading htmx site regularly on my phone (pixel 4a) and site looks as it could be improved. Because of font size, weight and multiple alignment lines, readability on not-too-big screens could be improved.
This PR suggests a couple of changes in style:
* Base `font-size` of `16px` - on small screens current font size results in very small part of the content being visible
* Additional `padding-bottom` of `5em` for body - on some pages content ends up direcly at the end of the window; having small margin at the bottom makes it easier to read last line and visually …
> Style changes proposal

- www/talk.md
Fixes header margins.
Current style sets no margin for first child (https://github.com/bigskysoftware/htmx/commit/b3dbb999#diff-5de0d55baacf311719c2102f912d06ecf3c7c24f023dc6af8f32e2f0a7a9cd41R133).
> Proposal: talk page in single column

- www/migration-guide-hotwire-turbo.md
Offsite link to hyperscript.org.
> Docs: Updated broken link.

- src/htmx.js
> fix extended attribute form for hx-ext in findElementsToProcess

- www/essays/template-fragments.md
This PR adds the link to the ASP.NET Core MVC Razor Partial Views.
@1cg should I add the sample together with this PR or create another PR?
> Add ASP.NET Core Razor Partial View docs

- www/essays/template-fragments.md
There are two packages I created specifically for integrating HTMX with Python web frameworks like Flask, FastAPI, Pyramid, etc. This PR adds links to them in the _known implementations_ section.
> Add Michael's partials projects for Python section

- www/essays/template-fragments.md
Since the discussion on jinja partials, @sponsfreixes created this nice direct implementation. 
https://github.com/sponsfreixes/jinja2-fragments
This PR suggests adding it to the list.
> Add Sergi's jinja_fragments package to Python list

- www/extensions/alpine-morph.md
ref: https://github.com/bigskysoftware/htmx/issues/985#issuecomment-1195145966
> doc: add note to alpine-morph example

- www/extensions/alpine-morph.md
ref: https://github.com/bigskysoftware/htmx/issues/985#issuecomment-1195145966
> doc: add missing import in alpine-morph example

- www/server-examples.md
This adds a link to the example code of Wim Deblauwe's [TODO MVC implementation using HTMX, Spring Boot and Thymeleaf ](https://www.wimdeblauwe.com/blog/2021/09/20/todomvc-with-spring-boot-and-thymeleaf-part-1/)(which is really great example of HTMX's power).
> additional spring boot based example link

- www/essays/hypermedia-driven-applications.md
A small overlook from the change in 3a21ec092.
> Small grammar fix in the HDA essay

- www/examples/infinite-scroll.md
> Added note about css overflow to infinite scroll example

- editors/jetbrains/htmx.web-types.json
- package.json
Hi! I hope you'll find this finishing touches useful and you'll be able to ship Web Types with your library. I haven't touched any config file to actually include Web Types file as I am not sure how you build the package.
It would be cool to actually generate documentation from MD files, so if you would like that, I can experiment a bit and try to dynamically produce Web Types during build. I would only need to know into which file I should plug-ing the generation code :)
> Web Types: rename, update schema, add css classes and register in package.json

- www/examples/active-search.md
Attribute change according to the explained example.
> fix typo attribute

- www/attributes/hx-ws.md
Fix what seems to be a typo in the docs.
> Fix typo in hx-ws.md

- src/ext/loading-states.js
- test/ext/loading-states.js
> Fix loading-states event subscription to prevent saving loading states in history

- www/attributes/hx-sse.md
Fixes verbiage under "Data Only Events" in www/attributes/hx-sse.
> Verbiage correction.

- package.json
- src/ext/ws.js
- src/htmx.js
- test/attributes/hx-ws.js
- test/ext/ws.js
- test/index.html
- www/extensions/web-sockets.md
Implements events support as per #1110
> Add events support for WebSockets

- www/_includes/layout.njk
I was struggling to find the twitter for updates. 
So I add it on footer
> add twitter on footer

- src/htmx.js
- test/core/regressions.js
fix for #1186 
Tests aren't passing - can't figure out how to submit the form based on enter key
> Hotfix for swapping fields that don't support setSelectionRange

- scripts/www.js
This was not done when submitting #1126, which lead to red tests on dev page
> Add websocket mocking library to www.js script

- www/attributes/hx-sync.md
> Fix typo for the hx-sync documentation

- src/ext/class-tools.js
I ran into this issue [here](https://github.com/bigskysoftware/htmx/issues/917) and, following the advice laid out in the linked article, I moved the procedures relying on setTimeout into their own functions and it now appears to be handling all the operations.
> class-tools extension only handling the last operation fix

- README.md
(And very minor formatting clean-up.)
> Closes #1243: Document Python 2 dependency

- src/ext/sse.js
- www/reference.md
> Trigger event when a SSE-source is opened

- www/_includes/layout.njk
- www/css/site.css
Implements https://github.com/bigskysoftware/htmx/issues/1328
https://user-images.githubusercontent.com/24665/229327333-1dc75e2f-0110-4bc9-9ea5-9677ea25a610.mp4
> Replaced website search with Google, similar to hyperscript.org. Removed anemic Algolia, docsearch.

- www/content/server-examples.md
> add awesome-python-htmx to resource list

- www/content/server-examples.md
flask-htmx is a Flask extension to work with htmx.
> Add link to flask-htmx resource

- www/static/_redirects
See: https://github.com/bigskysoftware/htmx/issues/1372
> Missing URL aliases for Locality of Behavior / Behaviour variations.

- www/content/docs.md
> Fix link to 3rd party section

- www/content/server-examples.md
This will include CodeIgniter 4 example:
* https://github.com/michalsn/codeigniter-htmx-demo
> Add PHP section to server-side examples

- www/content/examples/modal-custom.md
> Fix typo in custom modal example

- www/content/_index.md
- www/content/attributes/hx-sse.md
- www/content/attributes/hx-ws.md
- www/content/essays/a-response-to-rich-harris.md
- www/content/essays/when-to-use-hypermedia.md
- www/content/posts/2020-11-24-htmx-1.0.0-is-released.md
- www/content/posts/2020-6-30-htmx-0.0.7-is-released.md
- www/content/posts/2023-06-06-htmx-github-accelerator.md
- www/content/talk/index.md
```diff
- Github
- github
+ GitHub
```
> Fix GitHub word capitalization

- www/content/essays/_index.md
Group the essays by their subject matter, to make them a little easier to peruse.
> Group essays by subject

- src/htmx.js
- test/core/headers.js
- www/content/reference.md
> Implementation of HX-Reselect

- www/content/essays/template-fragments.md
Support was merged in https://github.com/mitsuhiko/minijinja/pull/262.
> Add Rust/MiniJinja to template-fragments.md

- www/themes/htmx-theme/static/css/site.css
> Add background-color to body element

- www/content/attributes/hx-trigger.md
Fixed documentation for `throttle` in response to https://github.com/bigskysoftware/htmx/issues/743#issuecomment-1126155417
> Update hx-trigger throttle documentation

- www/content/examples/modal-bootstrap.md
After some experimentation I managed to get htmx working smoothly with Bootstrap 5 modals and their original JS bundle.
Edit:
OK, got it working after few tries. Turns out the initial skeleton needs to be a bit bigger. But it doesn't require writing any JS or even using hyperscript :slightly_smiling_face:
> Cleaner Bootstrap 5 modals example.

- www/content/server-examples.md
> Add Kotlin examples to server-examples

- www/content/essays/_index.md
- www/content/essays/no-build-step.md
Wrote an essay about why htmx does not currently have a build step. Feedback and corrections very much appreciated.
> Add "Why htmx Doesn't Have a Build Step" essay

- www/content/extensions/multi-swap.md
"With OOB is not possible" -> "With OOB, it's impossible"
> Fix typo in multi-swap.md

- www/content/docs.md
- www/content/examples/_index.md
- www/content/examples/file-upload-input.md
Improve documentation for form submission with binary data.
> Add example of how to structure binary-data forms without data loss

- www/content/server-examples.md
Simple todo app using Elixir, Bandit, Plug and Htmx
> Add another Elixir example to server-examples.md

- src/ext/client-side-templates.js
- test/ext/client-side-templates.js
- www/content/extensions/client-side-templates.md
Fix Handlebars template rendering (see issues #801 and #1801).
> Fix Handlebars template rendering

- www/content/examples/modal-bootstrap.md
> Fixed indentation/rendering in Modal bootstrap example page

- src/ext/ws.js
- test/ext/ws.js
> Fix websocket polling trigger

- www/content/server-examples.md
- Added a Django server example link to "How to create a Django form (using HTMX) in 90 seconds 🐎".
- This article has received over 10k views, positive comments, and was featured in Will Vincent and Jeff Triplett's great weekly newsletter, "Django Newsletter" - which goes out to around 4k Django developers. 
I wrote the guides for my imagined former self. I would have benefitted from reading it when I was learning to use HTMX. 
Let me know if you'd like me to change anything ✍🏿
> Added a server example link to "How to create a Django form (using HTMX) in 90 seconds 🐎"

- src/htmx.d.ts
> Add new config options to typescript defs

- www/content/examples/_index.md
> Fixed typo in examples

- test/core/ajax.js
- test/core/events.js
- test/core/extensions.js
- test/core/internals.js
- test/core/perf.js
- test/core/regressions.js
- test/core/validation.js
- test/ext/hyperscript.js
- test/ext/ws.js
- test/index.html
- test/util/util.js
As discussed with @1cg, removed special checks in tests that were specific to IE, as we're going to drop support for it
> Removed IE-specific tests

- www/content/docs.md
See issue
Corresponding issue: https://github.com/bigskysoftware/htmx/issues/2043
> Mention response-extension in /docs extensions table

- www/content/webring.md
Add Gophemeral.com to the site list in webring.md.
* [ x ] I have read the contribution guidelines
* [ x ] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
* [ x ] This is either a bugfix, a documentation update, or a new feature that has been explicitly
> add gophemeral to the webring sites

- www/themes/htmx-theme/templates/base.html
> Add missing doctype

- www/content/essays/_index.md
- www/content/essays/is-htmx-another-javascript-framework.md
> Add "Is htmx Just Another Js Framework" Essay

- www/content/essays/mvc.md
> Fix typos in mvc.md

- www/content/essays/mvc.md
Related to:
* #2208
% `codespell --ignore-words-list=hda,revered --skip=www/content/examples/active-search.md **/*.md`
* https://pypi.org/project/codespell
> Fix typos in the MVC essay

- www/content/examples/edit-row.md
This PR fixes the logic in the edit-row example.
Corresponding issue: https://github.com/bigskysoftware/htmx/issues/2223
I have tested it locally.
> Fix edit-row example

- www/content/webring.md
Adding [signup.casa](https://signup.casa/) to the webring
> Add signup.casa to webring

- www/content/server-examples.md
[htmx-examples-with-flask](https://github.com/Konfuzian/htmx-examples-with-flask) contains htmx examples from the official website using Flask.
> Add link to `htmx-examples-with-flask` resource

- www/content/server-examples.md
Adding F# Giraffe Serverside example
> [Documentation] Server Examples: Add F# - Giraffe example

- CHANGELOG.md
> Fix date in CHANGELOG.md

- www/content/docs.md
fix #2457
Corresponding issue: #2457
> Add reference to unminified CDN distribution to the docs

- www/content/essays/rest-explained.md
In the example code the ID `42` was used, in the description it was suddenly the ID `1`.
> use same ID throughout the example

- CONTRIBUTING.md
Noticed a typo while reading instructions in `CONTRIBUTING.md`. Contributing a fix for the doc.
> Fix a trivial typo in CONTRIBUTING.md.

- test/attributes/hx-ext.js
> Add tests for getSelectors method for extension registration

- www/content/docs.md
A little fix in documentation 
> 📚 fix code sample in documentation

- www/content/attributes/hx-request.md
Simple docs update. Matches what is described and removes unnecessary quote escaping. 
Corresponding issue: [https://github.com/bigskysoftware/htmx/issues/2594](https://github.com/bigskysoftware/htmx/issues/2594)
> Fix: 2594 docs update

- www/content/server-examples.md
Adds rust example to `server-examples.md`
> Add rust example to server-examples.md

- www/content/essays/web-security-basics-with-htmx.md
The current version refers to an HTTP response as a request. Fixed it.
> fix minor mixup in the web security basics essay

- CONTRIBUTING.md
This change documents how to set up a development environment for working with htmx.
Corresponding issue: N/A
N/A
> Document software requirements for developing htmx

- www/content/events.md
Update `beforeHistorySave` docs
Adding the documentation update as suggested in the issue
#2688 
Visually
> Update `beforeHistorySave` documentation

- www/content/server-examples.md
Added a new FastAPI example that uses TailwindCSS and DaisyUI, and features active search, server-sent events, lazy loading, and server-side HTMX triggers among others.
> Added a FastAPI + TailwindCSS + DaisyUI example

- editors/jetbrains/htmx.web-types.json
> Correct hx-delete doc-url to https://htmx.org/attributes/hx-delete/

- www/content/examples/click-to-edit.md
> fix: example buttons in darkmode

- www/content/examples/update-other-content.md
Encountered a small typo while reading through the documentation that I thought I'd fix.
Corresponding issue: N/A
* [ x ] I have read the contribution guidelines
* [ x ] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
* [ x ] This is either a bugfix, a documentation update, or a new feature that has been explicitly
* [ x ] I ran the test suite locally (`npm run test`) and verified that it succeeded
> Fix typo in update-other-content.md

- www/content/server-examples.md
Add extra F# server examples links to docs
docs update
* [?] This is either a bugfix, a documentation update, or a new feature that has been explicitly
> add F# server-examples

- www/content/attributes/hx-preserve.md
Improve hx-preserve documentation after the recent updates done in #2934.  Move the additional detail into the notes section to tidy things up and add notes for other cases and problems i've found with hx-preserve.
#2934 
> improve hx-preserve documentation

- CONTRIBUTING.md
The existing command provided doesn't work and in the #htmx-dev channel on Discord I was informed what it should be.
At least this proves I read the guidelines!
I checked for it in package.json and then ran it to verify it works.
> Correct lint command in contribution guidelines

- www/content/server-examples.md
Added link to a project which recreates the contact-app using Blazor SSR
Short video about the project here: https://www.youtube.com/watch?v=G2Gkc27nWj8
> Add link to contact-app built in Blazor

- www/content/server-examples.md
I've added htmgo to server examples because it is a good project for using htmx with go.
I ran the website locally and verified it showed up correctly.
> Add htmgo to server examples

- www/content/essays/template-fragments.md
> Added Jeasx example for template fragements

- www/content/essays/codin-dirty.md
fixed minor typo "and" --> "an"
> fixed minor typo "and" --> "an".md

- www/content/extensions/response-targets.md
- www/content/extensions/sse.md
Corresponding issue: https://github.com/bigskysoftware/htmx/issues/3041
> [Documentation] Fix outdated attribute links

- www/content/server-examples.md
Adding https://github.com/mikaelstaldal/htmx-http4k-thymeleaf as server example for Kotlin.
> Add http4k server example

- www/content/docs.md
> Update docs.md to fix dead link

- www/content/QUIRKS.md
Just fixing a typo I found in the docs.
I didn't :grimacing: 
> fix QUIRKS.md typo

- www/content/essays/vendoring.md
- www/content/essays/view-transitions.md
These external links are broken.
> Fix some external links

- www/content/QUIRKS.md
Sorry about my editor deleting all those trailing spaces
> Add "less htmx" link

- www/content/attributes/hx-headers.md
- www/content/docs.md
Documentation typo correction.
None
> Documentation typo correction

- www/content/essays/alternatives.md
> Small fix on alternatives.md

- www/content/examples/bulk-update.md
- www/content/examples/edit-row.md
Autofocus when editing, and update text to match example code.
> Adjust examples

- www/content/extensions/_index.md
Added link to htmx-json extension
https://github.com/mariusGundersen/htmx-json
> Added extension

- www/content/server-examples.md
Add a link to actix-htmx to `server-examples.md`
> Update Rust server examples with actix-htmx

- www/content/webring.md
Adds [DankMuzikk](https://dankmuzikk.com) and  [DankLyrics](https://danklyrics.com) to the webring.
Source code:
* [DankMuzikk](https://github.com/mbaraa/dankmuzikk)
* [DankLyrics](https://github.com/mbaraa/danklyrics)
> Add DankMuzikk and DankLyrics to webring.
