bigskysoftware/htmx

www/examples.md
The description for the "Inline Validation" example appeared like it was duplicated from the "Lazy Loading" example's description. The wording may not be ideal, just creating so that it's tracked.
=> Update inline validation example description

src/htmx.js
The prompt command returns null in this case.  Note that empty string
is a valid return value, so we can't just check the boolean nature of
the return.
=> Cancel the AJAX request when user cancels prompt

src/htmx.js
This is a rather odd one, and a silly rabbit hole to get drawn into, but I noticed in #16 that submitting an empty string resulted in the "server" echoing `undefined`.  It looks like there were several assumptions that the header values, and specifically the response to the prompt, must be truthy.  Empty string is a valid response, so that's not the case.
This may be such a corner case that it's not worth fixing.  But it appears to be fixable without getting too involved.
=> Allow request to have empty header values

www/examples.md, www/examples/dialogs.md
Having both dialogs on the same element is not realistic, but it seemed like a cheap way to demonstrate both.
=> Add example of prompt and confirm dialogs

src/htmx.js
In accordance with the docs at https://dev.htmx.org/docs/#request-headers.
=> Renamed `Current-URL` header to `X-HX-Current-URL`

src/htmx.js, test/attributes/hx-trigger.js, www/attributes/hx-trigger.md, www/docs.md
Multiple triggers are now allowed in the `hx-trigger` attribute, separated by commas.  If now trigger can be parsed out of the attribute, we fall back to the default trigger for that element type.
The trigger spec is now a list of triggers, instead of just one.  Additionally, the `.trigger` attribute for repeating and SSE events are now set to "every" and "sse", instead of "click", as they had been before.
Note that options apply only to the particular trigger they are applied to.  Perhaps this is worth thinking about more.  I could see an argument that delay, for example, is likely to be desired the same for all events.  The current system does offer more flexibility, though.
Each trigger is used to start an event listener on boosted elements.  I'm not at all sure that this was the right …
=> Allow multiple triggers

src/htmx.js
I don't think this was causing any problems, but it could confuse anyone watching the event.
=> Switch afterRequest to standard event from error event if no error

src/htmx.js
No test written, but should fix https://github.com/bigskysoftware/htmx/issues/23.
=> Allows for empty verb attribute path

src/htmx.js, test/attributes/hx-ws.js, test/core/headers.js, test/manual/confirm-and-prompt.html, www/attributes/hx-prompt.md, www/attributes/hx-push-url.md, www/docs.md, www/examples/dialogs.md, www/headers/x-hx-trigger.md, www/js/htmx.js, www/reference.md
This convention is deprecated, as per [this RFC](https://tools.ietf.org/html/rfc6648).
tl;dr – prepending custom headers with `X-` doesn't make them any clearer, and can present problems if your custom proprietary headers ever get standardized. [More from MDN.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers)
=> Rename custom HTTP headers to no longer start with `X-`

www/docs.md
The polling section has example containing a `trigger` attribute. Updated this attribute to be `hx-trigger`.
=> Fix docs.md `trigger` attribute in polling section

www/attributes/hx-sse.md
=> fix hx-sse trigger in example

src/ext/ajax-header.js, test/ext/ajax-header.js, test/index.html, www/extensions.md, www/extensions/ajax-header.md
This extension adds the X-Requested-With header, which is used by many javascript frameworks to identify ajax requests.
Specifically for my use case, laravel has helper functions to determine if a request was made through ajax that look at this header.
=> Add an extension to include the commonly-used X-Requested-With header

src/ext/morphdom-swap.js, src/htmx.js, test/ext/index.js, test/ext/morphdom-swap.js, test/index.html
When swap was handled by an extension via its `handleSwap` method, a few expected things didn't work:
- `afterSwap.htmx` and `afterSettle.htmx` events where not propagated to `onLoad` methods of extensions
- `load.htmx` was not called for newly added elements
- new content in the target was not handled by `htmx`, so for example if an element with ` hx-trigger=load` was included, nothing was done about it.
This is fixed in this PR, the work being split in two commits that touch two independent things.
See the description of these commits to know for each what the problem was, what was expected and how it is handled.
=> Handle events and content after `handleSwap` in extensions

src/htmx.js, www/docs.md
This makes the `htmx-indicator` and `htmx-request` classes customisable, both in meta tags _as well as_ directly in JavaScript. To accomplish this, the indicator styles are included on page load instead of immediately. Please let me know if this is unsafe to do for any reason @chg20.
=> Make indicator and request classes customisable

README.md
According to https://shields.io/...
> To use the Discord badge a Discord server admin must enable the widget setting on the server.
=> Replaced Gitter chat badge with Discord

src/htmx.js
There are some global references to htmx in the source. When loaded deferred this causes an htmx is not defined error. To fix this, I created the variable `htmx` with the object which gets return at the end of the module.
Fixes #170
=> Fixes htmx not defined when script is loaded deferred 

src/htmx.js, test/core/regressions.js
When having a dot in the id-attribute of the response, the handleAttributes function throws an Exception:
> DOMException: Element.querySelector: 'DIV[id=ViewModel.Test]' is not a valid selector
The issue is the attribute-value in the selector isn't quoted.
```javascript
var oldNode = parentNode.querySelector(newNode.tagName + "[id=" + newNode.id + "]");
```
This causes the exception when there is a dot in the value.
This PR fixes this issue and adds a testcase to the regressions test suite to demonstrate the issue.
=> Fix issue with unquoted id attribute in query selector

test/core/events.js
To make sure these are fired when using outerHTML swapping
=> new afterOnLoad and afterRequest tests

src/htmx.js
Currently, HTMX does not close all WebSocket and SSE connections when a node's innerHTML is swapped.  This pull request adds `closeConnections` calls into the `swapInnerHTML` function, so that connections are not leaked after content is swapped.
=> Close connections on swapInnerHTML

src/htmx.js, test/attributes/hx-target.js, www/attributes/hx-target.md
This adds the `find` selector option to the `hx-target` attribute which allows targetting child descendant nodes.
=> FEATURE: find selector option of the hx-target attribute

src/htmx.js
Removed second parameter from `processNode` that is redundant as it does not exist in the function definition.
=> Removed redundant parameter

src/htmx.js
This adds an additional check to `makeAjaxLoadTask` that focuses on the first element with the HTML standard "autofocus" attribute set.  This addresses one of the original requests in #154
I've put it right next to the makeAjaxLoadTask function for clarity, but it should probably be organized into a different place, next to other corresponding functions.
=> FEATURE: Support "autofocus" attribute when swapping content

test/core/ajax.js
Adds a test case to demonstrate that 304 "Not Modified" response should be treated just the same as a regular 200 "Ok" response.
This PR is a replacement for #188 which inadvernently included a bunch of other code (sorry)
=> Add test case

www/attributes/hx-indicator.md
=> Fixed typo in first line of CSS sample showing how to use a custom

www/attributes/hx-target.md
Should be `beforeend`, all lowercase.
=> Fix swap example in hx-target page

www/docs.md, www/extensions/event-header.md, www/reference.md
Fix some typos, and the location of the *event-header* extension as linked to in the latest release notes.
=> Some docs cleanup

www/examples.md, www/examples/modal-bootstrap.md
This PR adds an online demo for showing modal dialogs using Twitter Bootstrap.  
I can't get the SASS plugin working with eleventy, so I'm guessing about the global page CSS. It looks like the UIKit stylesheet may mess up the global look of the page. If this is a dealbreaker (or can't be fixed) then we may not be able to use this commit.
=>  Website: demo modal dialogs using Bootstrap

src/htmx.js
This PR allow expression vars to override raw parameters.
Before:
```html
<form hx-get="">
<inpup type="hidden" name="temperature" value="0">
<button type="submit" hx-vars="temperature: -23">Go sub-zero</button>
</form>
```
After:
```html
<form hx-get="">
<inpup type="hidden" name="temperature" value="0">
<button type="submit" hx-vars="temperature: -23">Go sub-zero</button>
</form>
```
=> Allow expression vars to override raw parameters

www/examples/modal-bootstrap.md, www/examples/modal-uikit.md
Inconsistent names were making these demos break.  This should clear things up.
=> Fixing typos

src/htmx.js, test/attributes/hx-include.js
This PR changes how `getInputValues()` works.
1. If a non-GET request, collect all input values from the enclosing form.
2. Concatenate the current element's value.
3. Concatenate all remaining values from explicit includes.
1. If a non-GET request, collect all input values from the enclosing form.
2. Collect the current element's value.
3. Collect all remaining values from explicit includes.
4. Merge values from step 3 with values from step 2 with values from step 1.
The key difference is that in a non-GET request, if an element is inside a form then that form's input field values will _override_ input fields that exist outside the form.
```html
<div hx-include="*">
<input hx-get="/" type="text" name="secret" value="abc">
<form hx-post="/" id="form-1">
<input type="text" name="id" …
```
=> Change how getInputValues() works

src/htmx.js, test/core/internals.js
I realized I'd duplicated the parseInterval function for another PR, then saw the the original function returns several kinds of values.  If the interval is parsed successfully, a floating point number is returned.  Otherwise, the original function may return a `null`, or `NaN`, depending on the particular circumstances.
This PR standardizes all errors to return `undefined` in event of any parsing errors, which should make it easier to inspect results.
=> More consistent parseInterval results

src/ext/path-deps.js, test/ext/path-deps.js, www/extensions/path-deps.md
This is to implement #286.
**TLDR**: Went with `PathDeps.refresh("/path/to/refresh");` in the end.
Keeping the rest here for historical purposes.
-----
By catering for a new custom event called `htmx:refreshPath`, we should be able to trigger the refresh of a specific path, e.g. 
- `htmx.trigger(document, "htmx:refreshPath", {path:"path/to/refresh"});`
- `htmx.trigger(document, "htmx:refreshPath", {path:"path/to/refresh/*"});`
I have not added any tests or documentation yet, happy to do so if this idea is deemed to be ok in principle.
**Note**: Since we're interested in triggering updates on all elements with the given path (or dependent paths), the element to trigger on is irrelevant, I just went with "document" in the example. Not sure if there's a better way
=> Extend path-deps extension to handle explicit path refreshes

www/_includes/layout.njk
- for now, this only affects the top navigation.  More elements can be preloaded in the future if we like how this works.
=> Website: Add preload elements to website navigation

www/reference.md
As part of the htmx 1.1.0 release, the following headers were removed:
- HX-Event-Target
- HX-Active-Element
- HX-Active-Element-Name
- HX-Active-Element-Value
This removes them from the documentation as well
=> Correct documentation to reflect removal of some request headers

src/htmx.js
This improves the `getInputValues` method by non overriding included element values with the main element's value.
This should make the `Two inputs are included twice when they have the same name` test, added in https://github.com/bigskysoftware/htmx/commit/10e068fcaa4bdcf3190a9eb818064dc08ba8f7a4, pass.
=> Improve `getInputValues` function

src/htmx.js, test/attributes/hx-preserve.js
In some cases that preserved element might not be existing in the document. It might be deleted by JavaScript or the element from server is first time to load into document.
=> Handle preserved element that might not be existing

src/ext/preload.js, test/manual/preload-fragment.html, test/manual/preload.html, www/extensions/preload.md
Updates to the preload extension that preload linked resources (images only, for now) included in the preloaded document (or HTML fragment).  Scripts and Stylesheets are not affected.  Tested on current versions of Firefox, Chrome, and Safari.
=> Preload Resources

www/docs.md, www/headers/hx-trigger.md, www/migration-guide.md, www/reference.md
* Fix URL for move from `X-HX-` prefix to `HX-` - not sure if this would need a redirect.
* Cover all three `HX-Trigger-*` headers in the page.
* Remove some redundant redundancy in the list of response headers
=> Improve HX-Trigger documentation

CHANGELOG.md
* Fix some `impages` typo and unclosed bracket
* The mixed indentation of the sub-lists didn't work in my markdown renderer - the second list wasn't indented. Instead, use semantic h3's for the two sections.
=> Improve 1.2.0 release notes

www/attributes/hx-ws.md, www/docs.md
When connecting to websockets, the previous format using optional prefix was:
`hx-ws="connect ws:/chatroom"`
If has been changed to:
`hx-ws="connect:ws:/chatroom"` or `hx-ws="connect:wss:/chatroom"`
Made this fix in the docs.
=> Updated to note that change in format and add info about optional prefix

src/htmx.js
Small PR to make SSE consistent with Websockets.  On htmx.js#L1082 we settleImmediately after oob swapping a websocket event.  For SSE events we also swap in content, but settling is missing which means that the node does not get processed properly.
=> settle on SSE Swap event

src/htmx.js, www/attributes/hx-ws.md
I leave this here for discussion. Please, let me know what you think about this.
- use the current host and port
- use ws for http and wss for https
- these changes allow sending cookies of the current site
Another benefit is ease of use during development (usually without TLS).
=> Completing websocket URLs

src/htmx.js
#385
Using
```
elt.getAttribute('href').indexOf('#') !== 0
```
instead of
```
elf.href.indexOf('#') !== 0
```
seems to be the right thing to do because the latter always returns true. The PR does not fix any bug but it does not break any existing tests either.
=> Use getAttribute("href") instead of .href in shouldCancel

www/js/demo.js
Showing the cursor as pointer makes sense in the examples. This makes it more obvious that you can switch to a previous faked http call.
=> Added style="cursor: pointer" here, too

src/htmx.js
But don't scroll if the link is an anchor
See bigskysoftware/htmx#407
=> Scroll to top by default when visiting boosted links

src/htmx.js
#413 
I double checked and I think the original PR (#385) fixed the use of`.href` but should have also changed `!==`to `===`. Using the latest version (1.3.1) when I click on `<a href='#'>` the page actually scroll to the top which is a big regression.
=> Fix logic of shoudCancel

src/htmx.js, test/manual/websocket-reconnect.html, www/api.md, www/attributes/hx-ws.md, www/docs.md
I noticed that htmx does not reconnect after the connection has been dropped for various reasons.
I added this functionality because during development/deployments, server restarts are quite common and page reloads add unnecessary delays to the feedback loop.
This patch also adds the possibility to configure the reconnect interval since different use-cases and stages requires different latencies, e.g. dev: 3sec, prod: 20-30sec (in my case). If you think of a chat-like web app, you might want even have 5-10 secs, whereas message boards/issue trackers could live with up to 60 secs or more.
So, I leave this here open for discussion.
EDIT:
As an addition, one could randomize the reconnect period (reduced server startup load). We then might need an additional config variable such as …
=> WebSocket Reconnect

src/htmx.js, www/api.md
Hi!
I ran into an issue today while HTMX to breath new life into a Jekyll site.
In development mode Jekyll HTML is served on `127.0.0.1:4000` while HTMX partials are coming from `127.0.0.1:9000`. I noticed that cookies were not sent to `127.0.0.1:9000`. Initially I suspected some problem with CSP, but it turned out that `XMLHttpRequest` objects need to have `withCredentials` set to `true`. After patching `htmx.js` locally cookies were sent as expected.
Since this might be useful for others also, I decided to submit this pull request.
Hope this is useful!
=> add withCredentials config option

src/htmx.js
When hx-boost is swapping the body, in some cases it fails with:
```
htmx:swapError
TypeError: Cannot read property 'tasks' of undefined
at htmx-1.3.3.js:526
at forEach (htmx-1.3.3.js:222)
at handleAttributes (htmx-1.3.3.js:520)
at insertNodesBefore (htmx-1.3.3.js:552)
at swapInnerHTML (htmx-1.3.3.js:624)
at swapOuterHTML (htmx-1.3.3.js:584)
at swap (htmx-1.3.3.js:652)
at selectAndSwap (htmx-1.3.3.js:715)
at doSwap (htmx-1.3.3.js:2284)
at handleAjaxResponse (htmx-1.3.3.js:2358)
```
because `swapOuterHTML` is not passing `settleInfo` to `swapInnerHTML`
=> Fix swap error when using hx-boost or swapping the body tag

src/htmx.js
This changes throttling so it doesn't wait to be fired when the event happens, _unless_ it has already been fired and a timeout is waiting to be executed to clean itself.
Please note this is a bit of a shoot in the dark as I'm editing this directly in GitHub and haven't tested it, and of course I'm not adding/fixing any automated tests. So it's just an idea. :P
=> Fix throttling to avoid delaying

src/htmx.js
metaKey is the Cmd key in MacOS, which is used for the same purpose of opening
a link in another tab.
So it should be also used to ignore clicks on boosted links.
=> Ignore meta key for boosted links.

src/htmx.js, www/api.md
useTemplateFragments is referenced as a property of the `config` object https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L162
however it's initialized outside of the `config` object: https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L38
Also updated the docs.
=> Fixes for `useTemplateFragments`

www/extensions/client-side-templates.md
client-side-templates: Add full HTML example and CORS warning
=> client-side-templates: Add full HTML example and CORS warning

www/server-examples.md
The linked example is really a demonstration of use with the FastAPI framework rather than jinja. "jinja" is a templating language, which can also be used in Django, Flask, etc.
=> Rename 'FastAPI' section in server examples docs

www/css/site.scss
The menu for the docs is rather long, and on Firefox the last few items are cut off. I added an overflow to the list and a max-height to it to scroll on smaller desktop viewports. Also added a margin to the bottom to allow set some space between it and the rest of the content on mobile screens.
=> Allow docs navigation to scroll on shorter screens

www/server-examples.md
Widen the list of examples for Python Django.
=> Docs. Add django-siteajax to server-side examples

www/docs.md
`source` is not present in the example, nor is that an attribute specified in the docs for `hx-ws`.
=> docs: typo in websockets example

www/attributes/hx-trigger.md
Typo in the description of the search example. The target id and the url didn't match betewwn text and example.
=> search example typo

www/docs.md
AlpineJS needs Kebab case registrations of HTMX events to work properly.
=> Make explicit that AlpineJS should register events in Kebab case

www/attributes/hx-swap.md
Instead of `swap:` I think you meant `show:`. Also changed the single quotes surrounding `:bottom` into backticks so it renders properly as inline code.
=> Fix typo in hx-swap.md

www/examples/inline-validation.md
This is to fix the inline validation example, as reported in https://twitter.com/lobre8/status/1435527467700207618.
The wording wasn’t consistent with what was written on the example.
Note that I haven’t tested the server interaction, but as it is a simple edit, I guess it will surely work.
=> Fix the inline validation example by using a post request

www/README.md, www/docs.md
Add `timeout` to the configuration section which was mentioned in the `1.5.0` release
=> Add `timeout` to configuration section in documentation

src/htmx.js, test/manual/intersect-test-eventHandler.html
This PR fixes the root: option of the intersect special event which is currently broken and adds a manual test to demonstrate the issue.
=> Fix root: option of the intersect event

src/htmx.js
=> Fix for double loading content on htmx reveal + boost + backbutton

www/docs.md
This just adds a small reminder to set Access-Control headers. I had some pain with this today, because when this doesn't work, there is absolutely no indication in the browser developer tools. The headers just appear in the network tab of the browser, but do not exist in javascript. Very confusing if it strikes you for the first time!
I'm sure there is more that could go into this section about caveats associated with CORS. I can add more if anyone wants to recommend things to add.
=> docs: document the use of htmx in a CORS context

www/attributes/hx-target.md
Added quick example for a link that can update itself using hx-target="this".
Issue #445
=> 445 - Add hx-target="this" example

src/htmx.js
In the [the docs](https://htmx.org/attributes/hx-trigger/) about hx-trigger, it is mentioned that you can use extended CSS selectors such as `from:closest <CSS selector>` and `from:find <CSS selector>`. This however leads to a syntax error and does not seem to be implemented in the `getTriggerSpecs` method for 'from'.
I have added this parsing to this section and in our demo it works as described.
=> Fixed :closest and :find extended css selectors on hx-trigger

package.json
> This still seems an open issue, right? NPM shows the TS badge, `package.json` mentions it, but the downloaded package doesn't contain the typings file.
_Originally posted by @qqilihq in https://github.com/bigskysoftware/htmx/issues/545#issuecomment-962667918_
This PR is a direct response to @qqilihq's comment for PR #545
=> This solves the mystery of the missing types file re npm package

src/htmx.js, test/attributes/hx-swap-oob.js, www/attributes/hx-swap-oob.md
resolves #634
Motivation for these change is described in more detail in the referenced issue.
The [`hx-swap-oob`](https://htmx.org/attributes/hx-swap-oob/) attribute can use a css selector to find its target in the document.
In the current implementation, it only swaps into *the first* element found matching that selector.
It would be useful to be able to target *every* matching element, for example when the request leads to an update of some value displayed in multiple places in the page (such as nickname, tags, ...).
Use `querySelectorAll` instead of plain `querySelector`.
Loop over the results and swap a copy of the supplied fragment into each of them.
I'm not very familiar with js and the structure/conventions of this repo so I'm not sure if I made the right changes in all the right …
=> swap into all elements matching the out-of-band css selector

src/ext/alpine-morph.js, www/docs.md, www/extensions.md, www/extensions/alpine-morph.md
This PR adds a new `alpine-morph` extension to htmx, similar to the existing `morphdom-swap`, but specifically for projects using Alpine.js to take advantage of Alpine's new lightweight [morph plugin](https://alpinejs.dev/plugins/morph).
=> Alpine morph extension

www/api.md
Added some info about how `htmx.ajax()` returns a Promise, which can be paired with a callback to execute code after the content has been inserted into the DOM.
=> add instructions for using `htmx.ajax()` with a callback

www/examples/active-search.md
Closes #715 
Hi,
This is my first pull request on this repository. I hope I am abiding by the repository's collaboration guidelines, please let me know if I should've proceded differently.
Following up on issue #715, I took the liberty to make the changes to the [active search example on the website](https://htmx.org/examples/active-search/), so as to have a case-insensitive search when searching for contacts. The idea is to convert both the search term and all the contact information (_First name_, _Last name_ and _Email_) to lowercase, before checking if the search term is part of any of the contact fields.
Here a screenshot of the changes when running the `eleventy` server locally:
As you can see, searching for `venus` also yields the contact with `Venus` as their first name (example …
=> Change active search example to be case insensitive

www/docs.md
Reflect correct value of [defaultSettleDelay](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L46) in docs.
=> Update info about `config.defaultSettleDelay`

www/extensions/web-sockets.md
Tiny change, it was still using hx rather than ws
@benpate does this look good to you?
=> Fix main websockets example attribute in docs

www/examples/active-search.md
The example did not use a search type input so no abilty to clear input. To do a new search on clear the search trigger was added.
Only thing now is that on clear it shows all results. This is how I use it myself but maybe not the intended use for the example.
=> Improve Active Search Example

src/htmx.js, www/docs.md
The script insertion method introduced in 1.6.0 is very clean and avoids using `eval()`, which is great. However, it breaks when using CSPs that require a nonce for inline scripts. While `evalScript` does try to copy all the incoming script's attributes, this doesn't work for nonce because a) it appears to be [filtered from the attributes](https://github.com/whatwg/html/issues/2369) and b) wouldn't actually match the nonce for the original page anyway, since each request's nonce is different in most setups.
The CSP `script-src 'self' 'nonce-9190f323fb54b166d23a0ad59387dabf' 'unsafe-eval'` used to work with HTMX, but no longer does if you were relying on inline scripts. Changing it to add 'unsafe-inline' would work, but at that point there feels like almost no point to having the CSP.
This …
=> Allow inline scripts to have a nonce added

src/htmx.js
This PR changes the content-type header for urlencoded form data
(hx-post) as proposed in #74 and #717.
From #74:
> Turns out, the parameter `charset` isn't allowed for mime type `application/x-www-form-urlencoded`. (For example, see discussion at [here](https://stackoverflow.com/questions/16819502/application-x-www-form-urlencoded-and-charset-utf-8) and [here](https://stackoverflow.com/questions/19694503/ajax-setrequestheader-content-type-application-x-www-form-urlencoded-and-ch).)
=> fix content-type header for urlencoded form data

package.json, src/htmx.d.ts, src/htmx.test.ts, www/api.md
I have been recently trying htmx with the TypeScript declarations (thank you for these, @paxperscientiam!)
Unfortunately, I noticed that these typings would expect me to import HTMX as follows:
```typescript
import { htmx } from 'htmx';
htmx.defineExtension('foo', { … }); // will not work
```
… while the library actually provides all the API in the default import, and thus my (already working) codebase rather uses …:
```typescript
import htmx from 'htmx';
htmx.defineExtension('foo', { … }); // works!
```
Triggered by this, I fixed the import to work as actually provided by the library (unless of course I'm overlooking something fundamental), and went the long way to extend the typings with all the functionality from the API documentation, and added tests based on the given examples.
I …
=> Fix and extend TypeScript definitions

www/examples/bulk-update.md
The example is using the `hx-put` attribute.
=> Fixed typo in bulk update example

www/attributes/hx-preserve.md
I mistakenly thought that I could mark a (third party) node with `hx-preserve` and it would be carried onto the next page, but this is not the case. This makes sense. I’ve tried to improve the documentation to reflect this, and make the behaviour clearer in general.
=> Clarify hx-preserve docs

src/htmx.js
#787 
This PR allows the execution of scripts of type `module`, and therefore the sequencial execution of
```html
<script src='URL'></script>
<script type="module">
function_from_module();
</script>
```
when the `<script>`s are dynamically executed by htmx.
=> Allow execusion of scripts of type module

www/events.md
=> succesful => successful in events.md

README.md, www/README.md
After trying to set up the project, I found that Node 16 is incompatible with the pinned version of node-sass, and node 15 must be used. This PR documents the requirement - perhaps an upgrade to Node 16 can be done after.
=> Document required node version

package.json
Level 9 is more compressed, and faster to decompress.
Before:
```
$ wc -c dist/htmx.min.js.gz
11615 dist/htmx.min.js.gz
```
After:
```
$ wc -c dist/htmx.min.js.gz
11596 dist/htmx.min.js.gz
```
Cor blimey, that's 19 bytes saved!
=> Use gzip level 9 compression

www/attributes/hx-swap-oob.md
The docs for OOB swaps notes that the attribute must be on a top level element, however this note is missing from the reference docs.
=> Update docs for OOB swaps must be specified in the top level of the response

src/htmx.js, test/core/api.js, www/api.md
Gives ajax calls the ability to pass a swap string to control swapping behavior
=> Adding swap argument for ajax calls

src/htmx.js, test/core/validation.js
Building on the changes in https://github.com/bigskysoftware/htmx/pull/288, submitting a form using a button containing the [`formnovalidate`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit#formnovalidate) attribute should also cause the form to skip validation.
=> Skip validation if form submit button has formnovalidate attribute

www/attributes/hx-swap.md, www/docs.md
Added a bit more info on the swap page to make it clear the focus scroll behavior is disabled by default so it should be enabled with the modifier, or changed globally and then disabled via the modifier.
=> Expand focus-scroll usage info

www/examples/confirm.md, www/examples/edit-row.md
Scheme-relative URL’s were invented when HTTPS was slow, so HTTP pages could load resources insecurely, but a little faster. There’s no need to use them now as HTTPS is fast, and everything should be secure.
=> Rewrite scheme-relative URL’s to https

www/server-examples.md
Two of the links in the server-examples.md doesn't work. One is 404, and one has been under maintenance for at least several days.
=> Removed two links that don't work

www/docs.md
oob-swap wasn't in the headers, making it hard to find, and incidentally a pretty important feature.
=> Add missing header

README.md, www/docs.md, www/extensions.md, www/index.md
As per #800.
* Recommend downloading htmx as the main way of installing it.
* Cover npm installation in a bit more detail.
* Note the downsides of unpkg.com and always recommend with the integrity SHA.
* Use `<script defer>` in all `<script>` examples. This tells the browser to defer the parsing and processing of the script until all content is on display, increasing performance. [See HTML spec diagram](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-defer).
=> Update installation instructions

www/attributes/hx-ws.md, www/reference.md
Link in the documentation index is pointing to `/extensions/websockets` and link from the legacy `hx-ws` page is pointing to `/attributes/extensions/web-sockets`.
They should both be pointing to `/extensions/web-sockets`
=> docs: fix links to web-sockets extension page

www/reference.md
"has been moved to an extension"
=> Fix a typo in reference.md

src/htmx.js
Let me preface this by saying I have no idea how to work with AMD and this might be totally wrong.
This should fix #854  and prevent multiple instances of htmx from loading and mucking with each other
=> Attempts to fix case when htmx is loaded multiple times into browser

src/ext/ws.js, src/htmx.js
* Implement proper `hx-trigger` support
* Expose trigger handling API to extensions
* Implement safe message sending with sending queue
* Fix `ws-send` attributes connecting in new elements (#859)
* Fix OOB swapping of multiple elements in response (#857)
* ~~Fix `api.shouldCancel` call (#846)~~ Fixed in eafd316d5f436a6dda4b3af4a89d85de20d537ba
=> Improvements in WebSocket extension

www/extensions/web-sockets.md
Add mention of message queuing mechanism, following merge of #863 
Expand on the topic of swapping logic (relevant to #858). Thought that it should better describe the proper way to customize swapping mechanism for WS messages
=> Update websockets extension documentation

www/server-examples.md
- Adds chapmandu/cfwheels-htmx-crud server example
=> cfwheels-htmx-crud-server-example

www/css/site.scss
Before / After, so code elements don't blend in so much with the background.
Hotwire does this in their own documentation for clarity, example: https://turbo.hotwired.dev/handbook/frames
=> Docs: Code element readability.

www/reference.md
Removed words while improving overall descriptiveness, consistency.
Added Essential Attributes, to ensure important attributes are not lost in the supplementary ones. Important for newcomers to htmx.
=> Docs: Reference guide readability. Essential attributes.

www/_includes/demo_ui.html.liquid
Fixed a little display annoyance where the bottom bar in examples is cropped:
=> Fix #demo-server-info's height

www/essays/template-fragments.md
As clarified in #1023, ASP.NET Core doesn't have the concept similar to fragments.
=> Remove ASP.NET Core from list

www/essays.md
Fix link from https://htmx.org/essays/essays/template-fragments/ to https://htmx.org/essays/template-fragments/
=> Fix link to template fragments essay

www/docs.md
Everything works out of the box as expected. Users that generate different responses for the same URL based on some header need to be mindful of the implications (for example using the Vary response header). This is mentioned because it's a common pattern to use the `HX-Request` header to render only an HTML fragment.
=> Add documentation about HTTP caching

src/htmx.js
I am running HTMX with hx-boost and the history cache disabled (it's important to not show stale content to my users unless my backend uses cache-control headers to do so, in which case I simply rely on the fetch being cached). However, during 'history cache misses', the page title is not properly set.
This fixes it (mirroring the logic in `handleAjaxResponse`).
=> Properly set title during history cache miss

src/htmx.js, test/attributes/hx-vals.js, test/attributes/hx-vars.js
This PR aims to fix the issue of the "unset" directive not working for `hx-vals` or `hx-vars` due to it being parsed as JSON.
See [this codepen](https://codepen.io/b-lenton/pen/NWYoQMo) for an example of `hx-vals="unset"` both causing an error and not unsetting the inherited values.
=> Allow 'unset' directive for hx-vals and hx-vars

www/attributes/hx-select-oob.md
Correct "info-detail" to "info-details" in the explanation to the hx-select-oob example.
=> doc: fix typo in hx-select-oob attribute example

www/attributes/hx-swap.md
Wrong spelt `htxm` changed to `htmx`.
=> doc: fixed typo on hx-swap page

CHANGELOG.md
make all attributes links point to website instead broken link
=> fix attributes links

www/reference.md
As suggested in https://github.com/bigskysoftware/htmx/pull/980#issuecomment-1190247556.
Also fix capitalization of "htmx", and tweak wording for clarity.
=> reference docs: add "core" terminology

src/htmx.js
In my error tracking system, I was getting `Response Status Error Code 403 from undefined`. I tracked it down to this line. As far as I can tell, `responseInfo.pathInfo.path` is never defined. I assume this should be `responseInfo.pathInfo.requestPath`
=> Fix error message for responseError

www/docs.md
=> fix typo in docs.md

src/ext/multi-swap.js, test/ext/multi-swap.js, test/index.html, www/docs.md, www/extensions.md, www/extensions/multi-swap.md
This extension allows you to swap multiple elements marked with the `id` attribute from the HTML response. You can also choose for each element which [swap method](/docs/#swapping) should be used. 
Multi-swap can help in cases where OOB ([Out of Band Swaps](/docs/#oob_swaps)) is not enough for you. OOB requires HTML elements marked with `hx-swap-oob` attributes to be at the TOP level of HTML, which significantly limited its use. With OOB is not possible to swap multiple elements arbitrarily placed and nested in the DOM tree.
It is a very powerful tool in conjunction with `hx-boost` and `preload` extension.
=> extensions: added new extension 'multi-swap' with mocha tests and docs

www/headers/hx-location.md
The code snippet in the [`HX-Location`](https://htmx.org/headers/hx-location/) docs don't specify the language so it's black text on a black background.
=> Fix code snippet highlighting in HX-Location docs

src/htmx.js
1. Since LocalStorage is bound to the origin (domain/protocol/port triplet), we can normalize the URL format used as a key for a history snapshot to reduce cache misses for the same URL referenced differently. E.g.: `https://mysite.com/about`,  `/about` and `/about/` are normalized to `/about`. 
4. Prevent potential key collisions in boosted relative links, by converting the href to a fully resolved root-relative path. E.g. a boosted anchor `shoe.html` in the directory `products` becomes `/products/shoe.html`.
=> Normalise history cache key URLs, and prevent collisions in boosted anchors that use relative links.

www/essays/hypermedia-friendly-scripting.md
Added a few readability suggestions and typo fixes. I also added a React component example, to help demonstrate how hypermedia is emphasized over the scripting of the hypermedia in the hyperscript example.
=> Readability suggestions and typo fixes

www/essays/template-fragments.md
Quarkus Qute now supports Template Fragments. Added link under `Known Template Fragment Implementations`.
=> Added Quarkus Qute fragments as one of the implementations

src/ext/preload.js
When a response's max-age is very short, it becomes stale and in this situation we may want to trigger preload every time instead of once.
This PR enables to write `preload="mouseover always"` and have preload trigger every time.
=> Ability to trigger preload always (not once)

dist/ext/preload.js
I was having some trouble getting preloading working on a fresh page load until making this tweak. But it worked fine after doing a single boosted navigation. This led me to believe there was an issue with how preloading was initialized on links. This may not be the right fix, but it seems to be working for me.
For context, the JS bundle (which contains HTMX) on my site (in an `<script async="true" ...` tag) usually arrives after the DOM is finished loading  , which probably has something to do with why this wasn't working. HTMX otherwise works fine.
=> [RFC] Trigger preload module on htmx:load

src/htmx.js, test/core/events.js
Previously, we passed the _element_ as the original event. I think this bug was introduced in https://github.com/bigskysoftware/htmx/commit/8bb0399052f5a52a49e9e4f0f9624d25f1c2e890.
We can easily fix this by actually using both arguments of the `handler` closure.
Let me know if there is a better way to write this test.
=> Actually pass original event on to `htmx:configRequest`

www/extensions/client-side-templates.md
Docs on the website for this page are currently rendering incorrectly because of faulty escaping of curly braces (line 80 is rendered has `<p> and  and </> htmx - high power tools for html and </p>`). Unfortunately, this fix breaks the rendering of the file on github (there are extra `{% raw %}` directives), but I think it's better than the other way around.
=> Escape curly braces in the example

www/extensions.md, www/extensions/ajax-header.md, www/extensions/alpine-morph.md, www/extensions/class-tools.md, www/extensions/client-side-templates.md, www/extensions/debug.md, www/extensions/disable-element.md, www/extensions/event-header.md, www/extensions/head-support.md, www/extensions/include-vals.md, www/extensions/json-enc.md, www/extensions/loading-states.md, www/extensions/method-override.md, www/extensions/morphdom-swap.md, www/extensions/multi-swap.md, www/extensions/path-deps.md, www/extensions/preload.md, www/extensions/remove-me.md, www/extensions/restored.md, www/extensions/server-sent-events.md, www/extensions/web-sockets.md, www/reference.md
Discord has seen many question about extension not working, primarily because extension script is not included on the page. This PR attempts to partially resolve this problem by putting installation instructions in a more prominent place
=> Docs: Move extension script URL to the start of the page

test/servers/ws/README.md
fixing a link mismatch error in the readme for the go lang example for websocket extension
=> fix a typo in test-ws example

www/docs.md
- Fixed "for simplicities sake" to "For simplicity’s sake".
- Fixed "The div has the same id in the original an in the new content" to "The div has the same id in the original and in the new content".
=> Fixed typo

www/docs.md
The `delete` value shows up on https://htmx.org/attributes/hx-swap/ but not on https://htmx.org/docs/#swapping... took me a little bit to realize it was a possibility.
=> Add `delete` to docs.md swapping list

src/ext/ws.js, test/ext/ws.js, www/extensions/web-sockets.md
Adds `wsConnecting` event along with two tests:
1. To ensure `wsConnecting` is raised as expected.
2. To ensure lifecycle event order is `wsConnecting` → `wsOpen` → `wsClosed`.
(If need be, tests can be refactored in the future so test 2, above, replaces the separate tests for wsConnecting, wsOpen, and wsClosed as it implies that they do pass. @Renerick, if you feel it’s helpful to carry out that refactor with this pull request, I’m happy to make the change; I just wanted to keep changes to a minimum.)
=> Closes #1241: Add wsConnecting event

www/examples/progress-bar.md
Closed two 'div' tags in the initial state code and in the response code that were never closed.
=> Closed open div's

dist/htmx.d.ts
The types incorrectly labeled the return type of `htmx.ajax` as being `void` when it, in fact, returns a `Promise<void>`
This just fixes that.
=> :label: types ajax return

src/ext/ws.js, test/ext/ws.js
The problem was twofold:
- Scope/methods were not bound to the object.
- There was a typo in the array name.
The PR fixes the issue and adds a test that demonstrates handling the `wsConfigSend` event, cancelling the event, and sending a separate message instead, using the `socketWrapper`’s `send()` method. (And tests for expected types of the other members of its public interface.)
=> Fixes #1246: ws extension socketWrapper methods are undefined

README.md
Since `1.8.6` Python 2 is no longer required: https://htmx.org/posts/2023-03-02-htmx-1.8.6-is-released/
This PR updates the reference in the `README.md` file.
=> Remove reference to Python 2 in README.md

www/server-examples.md
I recently created an example web app named [Bulldoggy: The Reminders App](https://github.com/AutomationPanda/bulldoggy-reminders-app) that uses htmx with FastAPI. I added a link to this project on the [htmx Server-Side Examples](https://htmx.org/server-examples/) page. I'd be honored if you included my example project on the site. Thanks for considering.
=> Added an example project for FastAPI

src/htmx.js, test/attributes/hx-trigger.js, www/attributes/hx-trigger.md, www/events.md, www/reference.md
Adds a new `htmx:trigger` event that is fired whenever an HTMX AJAX request would be fired. In addition, the `hx-trigger` attribute can be specified on an element without an AJAX request, in which case it will simply fire the `htmx:trigger` event on the action specified by the attribute, and do nothing else.
This pattern allows for specifying client-side actions that don't require a network request, while remaining within the HTMX control paradigm.
This is a revised version of #1320, based on the discussion about how best to integrate its ideas. This PR implements two of the four proposed concepts:
* Support "naked" hx-trigger, make processVerbs set up a "fake" requestHandler that immediately terminates.
* Trigger a new non-bubbling htmx:trigger event
```html
<button …
```
=> Add support for "naked" triggers and htmx:trigger event

src/htmx.js
Nullify unreachable references to dom nodes inside `setTimeout()` calls, to allow garbage collection to release memory once the nodes have been swapped out of the dom. This helps prevent detached nodes from accumulating after multiple swaps without a browser refresh, and results in lower memory use (in my testing).
=> Fix for memory leak

www/attributes/hx-target.md
This change updates `hx-target` docs by adding `next` and `previous` expressions introduced in version [1.8.0](https://github.com/bigskysoftware/htmx/releases/tag/v1.8.0)
=> Update hx-target relative positional expressions

src/htmx.js, test/core/ajax.js
I had a page with some svg tags containing colons characters. When swapping those tags, a javascript error occured:
```
ncaught DOMException: Element.querySelector: 'sodipodi:namedview[id='namedview3825']' is not a valid selector
```
This pull requests add proper escaping to tag name containing colons.
=> Escape colon characters in querySelector

www/themes/htmx-theme/templates/base.html
- Make all indentation consistent at 4 spaces
- Remove two spurious `<div>` tags
- Collapse `<div>`-wrapped links that fit in a single line
- Split a `<label>` with nested tags within into multiple lines
=> Normalize whitespace in base website HTML template

www/content/attributes/hx-on.md, www/content/reference.md
* Added `hx-on` to reference page.
* `hx-on` docs page: Readability, removed words, slimmed down examples
=> hx-on: Added to Reference page, and revised docs: readability, wordiness.

README.md
This change fixes the URL of the logo image in the README.md file.
=> fix: readme file logo url

www/content/essays/template-fragments.md, www/content/server-examples.md
I've put my repo 2nd in the list because it is more popular (going by github stars) than the ones below it, and is growing into a fairly comprehensive list of solutions. Nice feedback I've had includes - https://github.com/spookylukey/django-htmx-patterns/discussions/2#discussioncomment-4847375
Also added a deep link to the relevant page from the "Template Fragments" essay.
=> Added a link to spookylukey/django-htmx-patterns

www/content/essays/hypermedia-driven-applications.md
The library is now linked to the author's Github account.
=> Essay update: Twinspark has changed the address

www/content/extensions/_index.md
This PR fixes a pair of typos on the docs extension page.
=> Fix spelling of 'idiomorph' on the extensions page

src/htmx.d.ts
hi, we ran into these two type errors after upgrading to 1.8.6 and using `import htmx from "htmx.org"` rather than grabbing it off of `window`
the relevant documentation for each: 
1. [config scroll behavior](https://htmx.org/api/#config)
2. [ajax swap](https://htmx.org/api/#ajax)
=> Missing types 1.8.6

editors/jetbrains/htmx.web-types.json, www/content/reference.md
I noticed in the table shown in the reference index page was using `beforeEnd` instead of `beforeend` this could lead to confusion among the developers. The hx-swap detailed view shows it correctly. This small PR changes it to `beforeend`.
BTW, I'm loving htmx: it's just amazing!
=> docs: updating attribute table to use beforeend instead of beforeEnd

src/htmx.js
Currently the restored scroll position is set before the browser has been able to fully swap in and render new content; that means if the cached scroll position of the restored page _exceeds the height of the page you are navigating from_, then the scroll position may not be restored correctly. As it's a race between the page being rendered in time and the scroll position being set, the problem is intermittent and may depend on factors such as the complexity of the markup being rendered or available memory.
This PR simply defers setting the scroll position to the next 'tick', to give the browser time to do its thing.
=> History: restoration of scroll position on back/forward navigation

www/content/attributes/hx-delete.md, www/content/examples/delete-row.md
This issue has come up in the Discord a few times, as well as on GitHub: https://github.com/bigskysoftware/htmx/issues/1130
In part because [Mozilla suggets](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE#responses) a `204 - NO CONTENT` status code as an idiomatic response to the `DELETE` HTTP method, a lot of people come to HTMX (myself included) expecting that returning a `204` will remove the element that sent the delete request from the DOM.
The reason HTMX does not do this is because of an HTMX-wide policy that the `204` response essentially means ["do not swap"](https://htmx.org/attributes/hx-delete/), which is perfectly reasonable once you get to know how the library works. It's also, however, a recurring stumbling block for new users.
I think this can be easily …
=> Include note about 204 in hx-delete docs and examples

www/content/docs.md
Replace htmx:beforeRequest with htmx:configRequest
Fix #1444
=> Docs: fix typo in scripting example

.gitignore, src/ext/sse.js
This typo prevents listening on `htmx:sseOpen` event.
=> fix typo in sse event name

src/htmx.js
It seems this was fixed [in the SSE extension](https://github.com/bigskysoftware/htmx/blob/master/src/ext/sse.js#L282) as parameters are correctly ordered there, but `target`and `elt` are still inverted on the core lib's SSE implementation.
I know you're planning to move it out from the core for htmx 2, but htmx 1 needs some love too and its current state is wrong
=> Fix inverted elt / target for sse selectAndSwap

CHANGELOG.md, src/ext/ws.js, test/ext/ws.js
Fix #1396 
"Naked hx-trigger" feature causes event handlers added after https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L1938 to be ignored by https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L1412. Not sure what to do with this right now, but moving extension initialization sooner seems to fix the problem
=> Fix WebSocket extension trigger handlers initialization

src/ext/preload.js
I found that when using the `preload="preload:init"` attribute some requests were being dropped. Without the source element, the `body` is used for queuing and `hx-sync` can't be used to override the element.
FYI @benpate
=> Preload extension: Include preloaded node as 'source' for preload so hx-sync/queue works properly

src/htmx.js, test/attributes/hx-boost.js, test/core/api.js, test/core/regressions.js, www/content/api.md
New function to turn off the logger after using `logAll()`. I applied to this to the tests as well so that `logAll()` is only used in the specfic places where debug output is required. This makes the console output of the tests dramatically more useful when run from the command line.
Compare the two console outputs for the tests. Because the new one doesn't log every single `htmx` event, the (existing) errors are more obvious.
=> Add logNone function and apply it to tests

package-lock.json, package.json, test/util/util.js
Update the clearWorkArea function so that it doesn't error if there was never a work area set up to begin with. This was causing the `npm test` target to end with an error code.
The package-lock.json update happens on a fresh install with node 15, so I'm including it here to make sure that the tests passing is reproducible. I also set the engine to node 15. 
This PR is separate from #1504 for clarity, but with both commits applied to the head of the `dev` branch, you can run:
```bash
npm test && echo $?
```
And the test suite runs successfully in about 16 seconds on my MacBook Pro. Without the logging commit it takes much longer and one of the tests actually times out, which (I think) is because our test suite is currently emitting a really enormous amount of text.
=> Fix clearWorkArea test util function

src/htmx.js
Currently, htmx sends values in the request body for DELETE requests.
While this seems to be _allowed_, the [RFC](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.5) says:
>  A payload within a DELETE request message has no defined semantics;
sending a payload body on a DELETE request might cause some existing
implementations to reject the request.
And this is exactly what happens with a Golang backend. As [its doc](https://pkg.go.dev/net/http#Request.ParseForm) says: 
> For POST, PUT, and PATCH requests, it also reads the request body, parses it as a form [...]
> For other HTTP methods, or when the Content-Type is not application/x-www-form-urlencoded, the request Body is not read
A simple fix here is to handle DELETE requests like GET requests in the core, so the parameters get URL …
=> [Bugfix] Encode DELETE payload as URL params like GET, instead of using body

src/htmx.js
Currently, with the following setup:
```html
<body hx-sse="connect:/sse">
<div class="some-container">
<div hx-sse="swap:content">Content</div>
</div>
</body>
```
If the div defining `hx-sse` gets replaced _(for example, a request is issued and swaps the content of the `some-container` div, or whatever)_, its event listener is actually never removed from the event source defined on the body.
It seems to be an error there in the code, as it's also inconsistent with the other SSE check that's in [`processSSETrigger`](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L1689)
Here the code is
- first checking if the source should be closed (i.e, if the event source element was removed from the body)
- only if the source shouldn't be removed, then it checks if the target element is …
=> [Bugfix] sse listener removal if element isn't in body anymore

www/content/examples/animations.md, www/content/examples/bulk-update.md, www/content/examples/click-to-edit.md, www/content/examples/click-to-load.md, www/content/examples/inline-validation.md, www/content/examples/lazy-load.md, www/content/examples/progress-bar.md, www/content/examples/tabs-hateoas.md, www/content/examples/tabs-hyperscript.md, www/static/js/demo.js
See #1431 
This PR fixes a number of issues with accessibility practices in the examples section of the docs. Most notably:
- fix missing hrefs on links
- replace links with buttons
- add autofocus attribute to inline editing examples and "click to load"
- fix missing input labels
- make a progress bar a Proper Progress bar (aria attributes)
This is not an exhaustive fix of all issues that probably exist in the examples, but an effort to cover most obvious low hanging bugs
=> fix accesibility and keyboard navigation issues in examples

src/htmx.js, test/core/parameters.js, test/ext/json-enc.js, www/content/docs.md
Even though the semantics of request bodies for GET are undefined, it is legal to set request bodies for them. By default, GET form parameters should be encoded as URLs. If, however, an extension defines `encodeParameters`, that should override the default and set the request bodies for GET methods, just like it does for all the other HTTP methods.
Resolves: #1514, #1539
Wrote some new unit tests for `GET` requests that have `json-enc` enabled, and this PR fixes the broken `DELETE` one.
=> Add configs to choose between ecoding parameters in the URL or request body

www/content/examples/click-to-edit.md
Nothing major. While testing the first example, I stumbled upon this small discrepancy between the text description and the actual code.
=> [Documentation] Fix paths mentioned in description text of the "Click to edit" example

www/content/essays/rest-explained.md
**PR Summary**:
PR contains a simple fix to broken hyperlink found in the docs. There are extra parenthesis that should be removed. Relevant docs page can be found [here](https://htmx.org/essays/rest-explained/#sections-5-4-5-5-related-work-summary).
=> docs: fix link by removing extra parenthesis

www/content/attributes/hx-trigger.md
Just to make it clear that
`hx-trigger="keyup from:input"` will retrieve all inputs on the page and listen to keyup on each of them, while
`hx-trigger="keyup from:find input"` will only retrieve the first input child (as well as all the extended selectors described on the reference page)
=> [Documentation] Make it clear that `from` with a standard selector gets all matching elements

src/htmx.js
Some unsupported syntaxes on IE11 throw an exception on load and simply break htmx, preventing it from doing anything
FYI:
- shadowRoot direct reference without window prefix was added in **1.7.0**
=> this one doesn't throw an exception on IE11, but does on older Firefox versions
- Destructuring was added in **1.8.6**
- Arrow function was added in latest release, **1.9.3**
- For of + const was added in latest release, **1.9.3**
So it turns out, **htmx has been broken on IE11 since 1.8.6**
Btw, see [how to run IE11 with dev tools](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/ie-mode/)  now that Edge replaced it in case you'd like to try it out
I hesitated to submit this PR on master directly, let me know if I should have done so
=> [Bugfix] Fix ie11 incompatible syntax

package.json
The engine is intended to signify that node 15 should be used for development, but it's causing issues for people who `npm install` htmx and have node in "strict-engine" mode.
Resolves:  #1584
=> Remove engine from package.json

src/htmx.js
Event listeners added to an element via `hx-on` will not be removed in `deInitOnHandlers` as intended.
The reasons are as follows:
- in `addHxOnEventHandler`, the return value of `addEventListener`, which is `undefined`, was set as `listener` in the object pushed to `onHandlers`
- in `deInitOnHandlers`, the wrong keys were used to access event name and listener from an object contained in `onHandlers`
This PR fixes both these issues.
=> Fix: `hx-on` event listener clean-up

src/ext/response-targets.js, test/ext/response-targets.js
- Adds tests for HX-Retarget: 
- default behavior to override hx-target-4* attribute
- ignoring HX-Retarget when configured to do so
- Adds test for `responseTargetPrefersExisting`
- Fix typo and closes #1598
=> Add tests for HX Retarget and fix typo

src/htmx.js, test/core/security.js
This fixes #1176 
When dynamically adding hx-disable to an element from your custom code:
- If any trigger handler is triggered on an element, it first checks if the element is currently disabled or not. If it is, cleans up the element _(which removes all htmx listeners from it)_ & aborts the handler
- You can also call `htmx.process` right after adding the attribute, to force the clean up immediately
When **removing** hx-disable from an element from your custom code:
- You will have to explicitly call `htmx.process` to have htmx initialize that element and bind handlers again
Added test cases for `hx-disable` dynamic addition / removal
=> [Bugfix] Handle dynamically added hx-disable

src/htmx.js, test/core/headers.js, www/content/headers/hx-trigger.md
Adds support for comma separated list of event names to the `HX-Trigger` response header.
Currently, to trigger multiple events with that header, you have to use the JSON syntax, even if you don't have any additional data to send.
This change lets you specify a list of event names, separated by commas, without additional details, like so:
`HX-Trigger: event1, event2`
The syntax is similar to the one of the [`hx-target`](https://htmx.org/attributes/hx-trigger/#multiple-triggers) attribute, that also supports a comma separated list syntax
=> [New feature] Comma separated list syntax for HX-Trigger response header

www/content/attributes/hx-on.md
Currently the examples in the documentation for `hx-on:*` include camelCase event names, which as the documentation says itself won't work due to DOM attributes not preserving casing. I've updated the events in the examples from camelCase to kebab-case and added extra clarification to the documentation.
=> Fix hx-on:* examples to use kebab-case event names, add clarification

src/htmx.js
This fixes #1496 
Typing `formElement.anything` returns all inputs declaring that `anything` as their name, as an object or an array if there are several of them. You can observe this behaviour in [this JSFiddle](https://jsfiddle.net/rj13gmq5/)
This causes the mentioned issue in htmx when accessing an element's ID with a direct `element.id` call, as for a form, this would return all inputs using `name="id"`
- You can see the bugged behavior of the current htmx state in [this JSFiddle](https://jsfiddle.net/wingedpig/fjqguda1/17/) provided by the issue's OP
- You can then see the behaviour you would expect with the suggested changes in [this JSFiddle](https://jsfiddle.net/6qnfrtvp/)
=> [Bugfix] Fix references to element.id

src/htmx.js, test/attributes/hx-trigger.js
Resolves #1565 
Given the following code:
``` html
<form hx-get="/search" hx-target="#result" hx-trigger="keyup changed delay:250ms from:#searchInput, change">
<label>Search <input id="searchInput" class="flex-grow" type="search" name="search"></label>
<label>Category <select name="category">
<option value="A">A</option>
<option value="B" selected>B</option>
<option value="C">C</option>
</select>
</label>
</form>
```
- Current htmx behaviour on [this JSFiddle](https://jsfiddle.net/7ygfa9zn/)
=> You can see here how the request isn't triggered when typing in the input, only when the `change` event is fired _(which happens in my case, when focusing out the input)_
- New behaviour with the suggested changes on [this JSFiddle](https://jsfiddle.net/1xzg9yts/)
=> You can see here how the …
=> [Bugfix] Fix hx-trigger `changed` modifier along `from` clause

src/htmx.js, test/core/ajax.js, test/ext/ws.js
The suggested changes should fix the following issues:
- #1506
=> values of clicked submit buttons defining a name/value pair, are now correctly included in the request payload
- #1120 
=> Submit buttons/inputs using the [`form attribute`](https://developer.mozilla.org/docs/Web/HTML/Element/button) and placed outside a form, are now correctly included in the request payload when clicked
- #971 / #970 / #1337 
=> `form`, `a` and `input type="submit"` are now processed by htmx not only when the element has `chanceOfBeingBoosted`. This fixes the issue where you had to put `hx-ext` on the form itself, otherwise the button's own value wouldn't be in the payload.
Also, this doesn't seem to do any harm since it doesn't impact the default behaviour when no htmx logic should happen.
- …
=> [Bugfix] Fix submit buttons/inputs handling

www/config.toml, www/content/essays/10-tips-for-SSR-HDA-apps.md, www/content/essays/_index.md, www/content/essays/a-real-world-react-to-htmx-port.md, www/content/essays/a-response-to-rich-harris.md, www/content/essays/architectural-sympathy.md, www/content/essays/complexity-budget.md, www/content/essays/hateoas.md, www/content/essays/how-did-rest-come-to-mean-the-opposite-of-rest.md, www/content/essays/hypermedia-apis-vs-data-apis.md, www/content/essays/hypermedia-clients.md, www/content/essays/hypermedia-driven-applications.md, www/content/essays/hypermedia-friendly-scripting.md, www/content/essays/hypermedia-on-whatever-youd-like.md, www/content/essays/locality-of-behaviour.md, www/content/essays/rest-copypasta.md, www/content/essays/spa-alternative.md, www/content/essays/splitting-your-apis.md, www/content/essays/template-fragments.md, www/content/essays/two-approaches-to-decoupling.md, www/content/essays/view-transitions.md, www/content/essays/when-to-use-hypermedia.md, www/themes/htmx-theme/static/css/site.css, www/themes/htmx-theme/templates/essay.html, www/themes/htmx-theme/templates/page.html
Update the static site generator to include the date and author automatically as part of the essays. I made a couple changes to the underlying static structure to make this a little more seamless, including:
* New "essay.html" template for posts in `/essays`
* Added an author taxonomy (can eventually be author pages)
* Added Carson as the author of all the existing esssays
* Cleaned up manual date entires, where they existed
All this will make it easier to publish guest essays and sort the essays (chronologically, by topic, or by author) as the essay base expands.
Please excuse the couple posts where my editor removed trailing whitespace.
Resolves: #1622 
See the [netfliy preview page](https://deploy-preview-1654--htmx.netlify.app/essays/).
=> Add date and author to essay template

src/htmx.js
As discussed in Discord, use `origin` to compare whether it's the same site to have same behaviour as CSP check with protocol, hostname and port.
Updated `sameHost` boolean to be true if it's the same site, too.
=> Update same site security to use origin

src/htmx.js
It's a pretty common pattern to define trigger events using the `from:body` syntax.
The issue: this "body" selector currently results in a call to `document.querySelectorAll` inside [`querySelectorAllExt`](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L591)
While this may seem a negligible thing, it turns out that on large HTML pages, this makes the initial page load & parsing way slower.
- In [this JSFiddle](https://jsfiddle.net/Lysqa2m9/), using the current state of the lib _(open the developer console to see the logged execution times)_, I get in average the following:
`querySelectorAllExt called 5000 times with 'body', took 180 ms`
- In [this JSFiddle](https://jsfiddle.net/gcdhs27w/), using the suggested change, I get in average the following:
`querySelectorAllExt …
=> [Performance] Fast path to resolve body selector

src/ext/response-targets.js, test/ext/response-targets.js, www/content/extensions/response-targets.md
This PR implements #1564, enabling the `5xx` syntax for the response-targets extension.
I refactored the attribute detection logic to make explicit which syntaxes we support. I also added tests to cover all attribute syntaxes.
I updated the docs to note `5xx` as an alternative syntax, leaving the `5*` syntax as the prominent recommendation.
I noticed that while the original issue discussed the syntax `5xx` (double `x`), the extension currently supports `5*` (single asterisk). I hadn't previously noticed the gap between `*`'s wildcard semantics and `x`'s placeholder semantics. I elected to make single/double/triple characters work for both syntaxes (to minimize developer surprise), and we can document only most idiomatic `5*` and `5xx`. If you want me to do something different, let me …
=> Support hx-target-5xx syntax in response-targets extension

test/core/security.js
Fix the CI (our logs are so extensive the tests actually can't run with this on).
=> Remove logAll from tests

src/htmx.js
If HTMX is imported in a module the readyState is "interactive" so the extension processing happens too late. This would fix it.
Rebased version of: #1659
=> Add interactive check to ready event handler

test/core/api.js
This "resolves" a timing bug that was occurring in the CI, where these tests would run before the htmx was ready (only in the GitHub actions servers). Not proud of this as a fix but I would like the CI to work again ASAP.
The bug is related to the change from these PRs: 
* https://github.com/bigskysoftware/htmx/pull/1672
* https://github.com/bigskysoftware/htmx/pull/1659
I still think the behavior in these PRs is correct. As best I can tell from [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState), the `loading` state happens before all the deferred scripts are loaded but `DOMContentLoaded` fires after deferred scripts are loaded, even though the MDN page says "[loading] state indicates that the DOMContentLoaded event is about to fire". Which is what …
=> Move load tests to the bottom of the core file

test/core/api.js, test/index.html
Enabling logAll in just one test has the capacity to overwhelm the CI with log output, so we disable it if the webdriver is automated.
Added a `logAll` before and after making this change and it removed the output.
=> Disable logAll in headless mode

www/content/attributes/hx-select-oob.md
👋 I've been playing with HTMX in a side project and so far it's been pretty great! I had run into a use-case for using `hx-select-oob` with `afterbegin` swapping behavior but didn't see it publicly documented and discovered the behavior after diving into the source since I had a feeling it would support it somehow.
I found that behavior [here](https://github.com/bigskysoftware/htmx/blob/47af93bdb0c9f5d356e36fd6073e0b74d12b9242/www/static/test/1.9.0/src/htmx.js#L803-L808) and wanted try documenting it so it's easy for folks to find in the future.
=> Document hx-select-oob swap-strategy capabilities

src/htmx.js
Updated version of #1659 and #1681 based on conversation with @xhaggi.
Basically there's a gap between the `DOMContentLoaded` event firing and the document readystate updating to `complete`. If you look at some [stackoverflow answers](https://stackoverflow.com/questions/9457891/how-to-detect-if-domcontentloaded-was-fired#comment104655688_35996985) you can see that people _think_ these two things should be the same, but they are not.
Fortunately, it's not hard for us to track with a closure. `DOMContentLoaded` will only run after all the deferred scripts have been executed, so as long as we listen for it on the initial execution of `htmx`, we should be safe. For good measure, I ORed it with `getDocument().readystate === 'complete'`, in case someone is doing something insane like …
=> Track DOM content loaded for ready() function

src/ext/ws.js, test/ext/ws.js
Previously, ws.js used `ws-connect` element as target when collecting request headers. Now it correctly takes `hx-target` attribute into account
=> [websocket] pass hx-target id in the HEADERS

src/htmx.js, test/attributes/hx-on-wildcard.js, test/attributes/hx-on.js, test/attributes/hx-vals.js, test/attributes/hx-vars.js
This builds upon PR #1680
It fixes the cases in #1390, and causes the new tests as defined in #1679 to pass.
Before this, `hx-on` handlers would not be added or evaluated if `allowEval` was false, but the restriction didn't apply to `hx-on:*` attributes which would still be called. Also neither attribute triggered `htmx:evalDisabledError`.
This fix registers handlers for `hx-on` & `hx-on:*` still but applies `maybeEval` at the point of execution, so that `htmx:evalDisabledError` is triggered when `allowEval` is `false` ... this is consistent with the behaviour elsewhere in htmx, and allows `allowEval` to be toggled live and event handlers will disabled/enabled accordingly.
=> Fix hx-on/hx-on:* to suppress evaluation if allowEval is false

CHANGELOG.md
Fixes a typo in the new `hx-on:*` attribute.
=> Fix typo in attribute

CONTRIBUTING.md, README.md
Expanded our contribution guidelines to a `CONTRIBUTING.md` file, which is pretty standard. We're getting enough of the same kind of content that I want to give people more stable answers for why we do or don't merge PRs.
At some point I'll add issue and PR templates as well.
Feedback welcome, especially if you think anything is unfair, or poorly explained.
=> Expand contribution guidelines to separate file

www/content/extensions/preload.md
Added a note about `Cache-Control` response headers that allow the browser to cache the response.
This should help avoid confusion such as that reported in https://github.com/bigskysoftware/htmx/issues/689
=> Update preload extension docs

src/htmx.d.ts
This PR proposes including default config values in the types. The desired DX improvement is to make it easier to reference a property's default value, as the default behavior for IDEs is to jump to the type definitions and not the source code.
---
=> Include default config values in TypeScript definitions

www/content/events.md, www/content/reference.md
This adds a mention to the [htmx:beforeCleanupElement](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L955) event, which was missing from the docs
=> [Doc] Fix missing beforeCleanupElement event in doc

src/htmx.js, test/attributes/hx-disinherit.js
This resolves a bug with file system URLs on Windows. It reverts part of a previous change (#1338) where URLs were normalized prior to the request in order to reduce key collisions in the history cache. 
The gist is that on Windows, `elt.href` normalizes relative URLs like this:
```
Boost HTMLAnchorElement
href resolves to file:///E:/test
raw attribute : /test
should swap ? false
Response Status Error Code 404 from file:///E:/test
```
Why does `elt.href` normalize relative URLs on Windows file systems differently from how anchor elements normalize URLs? It doesn't. It normalizes the URL into something that is wrong (on Windows) before the `mockServer()` function can get to it. It turns this: 
```html
<a href="/profile">My Profile</a>
<a hx-boost="/profile">My Profile</a>
```
into this: …
=> Use raw attribute href on hx-boost

www/content/api.md
Adds the missing `allowScriptTags` config option.
=> Add `allowScriptTags` to docs

src/htmx.js, test/attributes/hx-boost.js
Bug: The these two forms should POST to the same URL but do not.
```html
<form>
<button formaction="/action" formmethod="POST">Submit</button>
</form>
<form hx-boost="true">
<button formaction="/action" formmethod="POST">Submit Boosted</button>
</form>
```
Fix: take into account formaction and formmethod of the submitter.
I'm not familiar with the HTMX codebase but `issueAjaxRequest` seemed like a reasonable place to handle this. ~`event.submitter` is relatively new as well, so you might want a more backwards compatible implementation, but this shows the gist of the issue and the fix.~
Instead of using event.submitter, I have opted to use the tracked button click on the internal data. This should work on all browser targets supported by HTMX.
=> Support formaction and formmethod on <button>

src/ext/client-side-templates.js, test/ext/client-side-templates.js, www/content/extensions/client-side-templates.md
Resolves #1775 by introducing `<template-engine>-array-template` renderers that can be used to work with APIs returning arrays of data.
=> Add support for array templates to the client-side templates extension

src/htmx.d.ts, src/htmx.js
According to the [docs](https://htmx.org/api/#ajax), the `htmx.ajax` function returns a `Promise<void>`, but the typedefs say it's just `void`.
This was once fixed in #1265 but it seems to have been overriden in 15d4cac.
=> Make htmx.ajax always return a Promise

src/ext/disable-element.js, test/ext/disable-element.js, www/content/extensions/disable-element.md
Allow multiple elements to be selected in the query
Better version of #1639 - this time I actually read the contribution guide
=> Allow disable-element extension to disable multiple elements

src/htmx.js, test/attributes/hx-swap.js, www/content/attributes/hx-swap.md
This makes the swap style `innerHTML`, `outerHTML` etc. in `hx-swap` optional and improves the handling of unknown values.
@David-Guillot you have requested something like that in https://github.com/bigskysoftware/htmx/issues/407#issuecomment-876543782
=> Allow hx-swap options to be used without specifying modifier (innerHTML remains the default)

src/htmx.js, test/attributes/hx-on.js
Unlike `hx-trigger`, `hx-on` does not support event names that contain dots.
```html
<div hx-get="/test" hx-trigger="my.custom.event" hx-on="my.custom.event: alert('Fired!')"></div>
```
Instead htmx throws a SyntaxError:
```
Uncaught SyntaxError: Unexpected token ':'
```
=> Support event names with "." character

src/ext/client-side-templates.js, test/ext/client-side-templates.js, www/content/extensions/_index.md, www/content/extensions/client-side-templates.md
This PR extends client-side-templates with XSLT support.
Uses browser built-in XSLTProcessor, so no external dependencies are needed.
Since this is only a fourth supported templating engine, I don't think it adds any complexity.
Please let me know if I can improve this in any way!
A couple of other things, which I didn't include:
I don't know how external script support for the other engines is supposed to work, but at least for XSLT it seemed to work using an object tag (see https://lahteenmaki.net/davtest/ for an example). However, I didn't include anything about it in the documentation since I guess the handling should somehow be unified across all supported engines, or what do you think?
I noticed that the HTML template tag is often not useful for templates (dah...) since the browser …
=> Extend client-side-templates to handle XSLT transformations

test/core/ajax.js
As per [a discussion in the discord](https://discord.com/channels/725789699527933952/1135615265640566794/1154097770362306610), I've realized that in the PR #1559 I had added a bunch of tests about submit buttons/inputs that are outside forms, using the `form` attribute, but none to make sure input _values_ outside forms also work.
They work as expected, but I thought we might just as well add a test case for this scenario too, to prevent any potential future regression
=> [Test] Add a test to ensure inputs outside form with `form` attribute work properly

src/htmx.js, test/manual/history_style/1.html, test/manual/history_style/2.html, test/manual/history_style/3.html, test/manual/history_style/4.html, test/manual/history_style/index.html, test/manual/index.html
I was playing around with htmx with a site that has styles embedded in weird places, and noticed that when I navigated through history, occasionally styles were disappearing.
After a bit of investigation I found `makeFragment(..)` and it all made (a bit more) sense.  I've attached a screen recording showing the new tests before + after the fix. I recorded it with firefox but I checked it in chrome + safari too. Don't have IE to check that . . .
https://github.com/bigskysoftware/htmx/assets/183554/2e1367a4-f4ea-44a9-87a0-3a64212e313a
=> fix problem with styles at the start of the server content

test/core/ajax.js, test/core/parameters.js, test/core/security.js, test/index.html
- Most important change is calling mocha run on DOMContentLoaded instead of directly from the inline script (it could run mocha before htmx initialized itself, that caused the 84 errors scenario, probably the 24 errors one too)
- Changed a few hardcoded setTimeouts to rely on event listeners instead
- Increased the timeout to 4s (formerly 2) on the 4 tests making a request to hypermedia.systems ; those were causing random local errors where the (at least my) network connection would apparently not be enough to fetch the page in less than 2s
=> [Tests] Fix test pipeline timing issues

src/htmx.js, test/core/extensions.js, test/index.html
As the title says, this PR adds support to cancel an event also with `preventDefault()` within `onEvent` of an extension.
=> Add support for event cancellation (preventDefault) in extensions

www/content/server-examples.md
Added htmx from alchemists.io. Works with any web framework. Also added a missing `-`
=> Update Ruby list of server-examples.md

www/content/attributes/hx-disabled-elt.md
https://htmx.org/attributes/hx-disabled-elt/
I think this was originally `hx-disabled-elts` and all the references to it were then changed to `hx-disabled-elts` except the reference in the notes, in the footer.
=> Fix reference in notes from `hx-disable-elts` to `hx-disable-elt`

www/content/docs.md, www/content/reference.md
The documentation seems complete in `reference.md` but the `docs.md` file lacked some attributes
=> Improve request/response documentation in docs.md

src/htmx.js, test/core/ajax.js
In the following example htmx will issue a `DIALOG` request instead of a `POST` request.
```html
<dialog>
<form hx-post="/test">
<button formmethod="dialog" name="foo" value="bar">Submit</button>
</form>
</dialog>
```
This PR changes the behaviour so that htmx will issue a `POST` request.
Closes https://github.com/bigskysoftware/htmx/issues/1859
=> Ignore formmethod when value is "dialog"

src/htmx.js
This addresses #1749 
- htmx uses [an internal data](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L2446) to keep track of the last clicked button in a form
- it [relies on the focusout](https://github.com/bigskysoftware/htmx/blob/master/src/htmx.js#L1911) event to clear that reference
- on Chrome, the focusout event gets called when the element is swapped and removed from the DOM
- however on Firefox for some reason, the event isn't fired at all, so the reference is never cleared, the internal state still has a reference to the removed button as the last clicked button, thus its values gets included, until you click out to focusout the form
This change adds a check right before using that `lastButtonClicked` property, making sure the referenced button is still in the DOM
=> Clear lastButtonClicked ref if it was removed from the DOM

src/htmx.js, www/content/events.md
This adds a new event `htmx:beforeHistoryUpdate` that is triggered right before the history is updated. It can be used to modify the `path` or `type` used to update the history.
=> Add new event htmx:beforeHistoryUpdate

src/htmx.js, test/attributes/hx-target.js, test/attributes/hx-trigger.js, test/util/util.js, www/content/attributes/hx-target.md, www/content/attributes/hx-trigger.md
I'm very often using the following pattern :
```html
<div class="relative">
<button hx-get="/some_popup" hx-target="nextElementSibling" hx-swap="outerHTML"></button>
<div class="popup"></div>
</div>
```
clicking on the button brings in a popup, in place of a initially empty element. The relative parent allows positioning the popup next to the button with a position set to absolute. Ending up with something like:
```html
<div class="relative">
<button hx-get="/some_popup" hx-target="nextElementSibling" hx-swap="outerHTML"></button>
<div class="popup visible">
<button>Action 1</button>
<button>Action 2</button>
Or whatever else...
</div>
</div>
```
Since the JS API exposes [element.nextElementSibling](https://developer.mozilla.org/docs/Web/API/Element/nextElementSibling) and …
=> [New feature] selector-less next and previous targets

www/content/examples/sortable.md
- Fix bug where, when an item is dragged fast enough before a previous request is completed, dropping it after the request's completion resulted in the addition of an extra item to the list. This is fixed by disabling the sortable on its `end` event, and re-enabling it on its `htmx:afterSwap` event.
Before:
https://github.com/bigskysoftware/htmx/assets/6943864/290ca6e8-8d17-42db-9fa7-1f58b75abffa
After:
https://github.com/bigskysoftware/htmx/assets/6943864/cafa81ec-8204-42ef-9a7d-af8e41835172
- Disable draggability of the `.htmx-indicator` ("Updating...") element.
Before:
https://github.com/bigskysoftware/htmx/assets/6943864/5f292592-5966-42ca-b7a4-312bac161e1a
After:
https://github.com/bigskysoftware/htmx/assets/6943864/e0eb73c4-4962-4bf8-b533-0d67587bdb46
- Indicate draggable items by …
=> Sortable example fixes

www/content/attributes/hx-sse.md, www/content/attributes/hx-ws.md, www/content/extensions/server-sent-events.md, www/content/extensions/web-sockets.md
This updates the `ws` and `sse` extension docs to match the changes made in the [recently merged PR](https://github.com/bigskysoftware/htmx/pull/1876) that updated the `ws` and `sse` test servers from Go to Node.js.
=> Fixed ws and sse references in the docs

src/htmx.js, test/core/ajax.js
Fixes form submissions of `type="email"` inputs with the `multiple` attribute. These inputs' values were previously being ignored because all inputs with the `multiple` attribute were assumed to be `select` elements.
I added one test in `ajax.js`, but I can add more in other places if needed.
closes #1912
=> Fix: form submission of email inputs with `multiple` attribute

src/htmx.js
Currently clicking the link on this:
```
<html>
<head>
<script src="https://unpkg.com/htmx.org@1.9.6/dist/htmx.js" ></script>
</head>
<body>
<a href="" hx-get="other.html#foo()bar">Click me</a>
</body>
</html>
```
results in
```
DOMException: Failed to execute 'querySelector' on 'Document': '#foo()bar' is not a valid selector.
```
on line 492.
Since responseInfo.pathInfo.anchor is assumed to be an ID here, use getElementById instead of querySelector to allow all characters.
I can't see any problems with this change, but please let me know if I'm missing something.
=> Fix: Use getElementById instead of querySelector to work with all valid characters

src/htmx.js, test/attributes/hx-confirm.js, test/core/events.js, test/index.html, www/content/attributes/hx-confirm.md, www/content/examples/confirm.md
Referring to #1588 
- Adds test for existing `hx-confirm` behavior by stubbing window.confirm; tests were added to a new test file `hx-confirm.js`
- Enhance `htmx:confirm` event detail to include the value found in `hx-confirm` (set to `detail.question`)
- Allow passing `skipConfirmation` to `detail.issueRequest`; when true, this skips window.confirm and triggers the request right away
- Fix the missing check for `confirmed` in original code (that was the original issue)
- Fix typo in [original `htmx:config` test ](https://github.com/bigskysoftware/htmx/blob/2534a970b6d606cb590edd8f6097e4a6440d8d06/test/core/events.js#L646) (incorrect handler would be removed in case of test failure)
Backwards compatibility: if `skipConfirmation` is not passed, the behaviour remains the same as it was …
=> Fix `confirmed` being ignored in htmx:confirm event

src/htmx.js, test/attributes/hx-on-wildcard.js, test/attributes/hx-on.js
This is the replacement PR for: https://github.com/bigskysoftware/htmx/pull/1862
Related to this discussion I created: https://github.com/bigskysoftware/htmx/discussions/1861
I started digging into the code a little and realised that nodeData.onHandlers can only hold one on-handler at a time since it is wiped every time addHxOnEventHandler is called. The fix is to just not do that if nodeData.onHandlers already exists.
This is fixes the cause of the problem in the linked discussion because when there are multiple on-handlers on an element, only the last one is stored. So then only the last on-handler gets removed when the DOM updates. Every other on-handler just gets re-added without getting removed beforehand.
=> fix: prevent nodeData.onHandlers overwrite

src/htmx.js
=> Clear cache when historyCacheSize is set to 0

src/ext/response-targets.js, www/content/extensions/response-targets.md
The hx-target-error attribute handles both 4xx and 5xx requests, allowing for simpler error handling.
=> Add hx-target-error attribute to response-targets extension

dist/htmx.d.ts
Add missing config settings to type declarations in dist/htmx.d.ts
=> Add missing config settings to type declarations in dist/htmx.d.ts

src/htmx.js, www/content/api.md, www/content/attributes/hx-swap.md
This adds a configuration option to enable/disable scrolling up after swapping a boosted link or form.
Related discussion https://github.com/bigskysoftware/htmx/issues/407
@David-Guillot you have requested something like that in https://github.com/bigskysoftware/htmx/issues/407#issuecomment-876543782
=> Add config option to disable scroll into view for targets of boosted links and forms

www/content/server-examples.md
`elem-go` is an HTML generation library written in Go that offers an integration with `htmx`. More information about this integration can be found in the `elem-go` documentation: [HTMX Integration](https://github.com/chasefleming/elem-go/blob/main/HTMX_INTEGRATION.md).
This PR that includes two example applications showcasing the combined use of `htmx` and `elem-go`:
1. **Counter Example**: Showcases a simple counter that can be incremented interactively.
2. **Todo List Example**: Demonstrates a dynamic todo list where tasks can be added and marked as complete or active.
Thanks!
=> Add htmx/elem-go server examples

scripts/www.sh, www/themes/htmx-theme/static/js/htmx.js
Kind of an emergency fix, see [this reported bug](https://github.com/bigskysoftware/htmx/pull/1610#issuecomment-1794835076)
- The website's htmx.js included in examples is currently outdated, it's using 1.9.5
- PR #1733 had replaced the old www js script by a new bash one, but it seems some copies [got lost in the way ](https://github.com/bigskysoftware/htmx/pull/1733/files#diff-5c1e18f5cb674fccbaffee74a972fbb1bfd76aec8a0a676367e4854445e3988fL31-L33)
- This PR adds those file copies again to the script
Note: I'm not familiar with Zola, but I wonder if we could get rid of those JS files at all and only use the ones in static instead? Wanted to avoid it for now as I'm not sure of the side effects
=> Fix www.sh, copy scripts to theme's static/js folder too

www/content/attributes/hx-include.md
This addresses issue #1509
- `hx-include` supports the extended selectors, which were not mentioned in its documentation
- The behaviour of `find` for example, can be confusing when using an inherited hx-include attribute: added a note to explain that
- Extended selectors only return a single element, which could be confusing compared to a standard CSS selector that returns all elements matching that selector: added a note to explain that
=> List extended selectors + caveats in hx-include doc

www/content/examples/active-search.md
Rebased version of #1181. Still has the original author in the commit.  
`keyup` only works with a keyboard, and ignores pasting with a right click or programmatically updating the value with JS. `input` is a better event for detecting any "inputs to the input".
=> Replace keyup with input event

src/htmx.js, www/content/api.md, www/content/docs.md
The configuration docs between the api reference and the docs reference are inconsistent, between each other but also with htmx.js:
- missing properties
- incorrect defaults (`disable-htmx` instead of `hx-disable`)
- 1 property was missing from htmx.config (`ignoreTitle`)
- different descriptions
- different order
This PR is an attempt to homogenize those 2 docs, consider it as a first step.
- ✅ missing properties
- ✅ incorrect defaults (`disable-htmx` instead of `hx-disable`)
- ~~✅ 1 property was missing from htmx.config (`ignoreTitle`)~~ => moved to a separate PR: #1981 
- 🚫 different descriptions
- 🚫 different order
Please note I didn't reorder the lines nor did I make all descriptions match.
I did so that it would be easier to see the diff and review the changes, let me know @1cg …
=> Homogenize configuration docs

www/content/docs.md, www/content/reference.md
Could not figure out how to import directly from docs.md with zola.
=> Add configuration options list to reference docs

test/core/ajax.js
Found while working on improving the js support of HtmlUnit.
This replaces [#1990](https://github.com/bigskysoftware/htmx/pull/1990)
=> Add missing '})' in core ajax tests

www/static/js/demo.js
I've fixed the www demo server to prevent returning unsanitized values wherever a request is made. When a 
It fixes https://github.com/bigskysoftware/htmx/issues/1131
=> Escape HTML on demo server

src/htmx.d.ts
=> Add config option scrollIntoViewOnBoost to typescript defs

src/htmx.d.ts, src/htmx.js, test/core/api.js, www/content/api.md
Created a PR for this issue https://github.com/bigskysoftware/htmx/issues/701 and saw that it was "add(ed) to a list" ([comment](https://github.com/bigskysoftware/htmx/issues/701#issuecomment-1013968132)). Hopefully this PR is helpful. Let me know if there are issues, I took some liberties in implementing it how I thought was best but I'm not sure if adding more properties to the `responseInfo` object is desirable. I added some tests and documentation. 
I thought the best API would be that the "HX-Reselect" header value should override the ajax api call but I wasn't sure. Let me know if that is incorrect. 
Htmx is a great project thank you for working on it!
=> Add `select` option to htmx.ajax()

dist/htmx.d.ts, src/htmx.js
This option was introduced by https://github.com/bigskysoftware/htmx/commit/c230931d42489a629d685bedb440fadd7eaf1416 which also [added documentation](https://github.com/bigskysoftware/htmx/commit/c230931d42489a629d685bedb440fadd7eaf1416#diff-e772080787482bb78eeddd4d3c75a4ecd414c5e06674fde21d4383c1c3927735R1635) for it, but it seems it was forgotten from the htmx.config object iself
That documentation itself states the following:
> defaults to false, if set to true htmx will not update the title of the document when a title tag is found in new content
So I simply added that default value of false in the config
=> Fix missing ignoreTitle property declaration in htmx.config

src/htmx.js, test/attributes/hx-trigger.js, www/content/attributes/hx-trigger.md
A CSS selector that uses the descendant combinator, e.g. `form input` to target an `input` that is in a `form`, causes an HTMX syntax error, as the parsing of the `hx-trigger` consumes tokens until it finds whitespace, at which point it will try to parse `input` as a token and flag it as invalid syntax.
As suggested in #569, we could allow for such selectors when wrapping them in for instance curly brackets or parentheses. 
I implemented this logic, allowing for either parentheses or curly braces to wrap a selector. This works for both regular CSS selectors as well as extended CSS selectors using e.g. `from`.
I'd like to have allowed for square brackets or single/double quotes as well, but since those are both used already when parsing `hx-trigger`, this wasn't possible.
---
Examples: …
=> Allow CSS selectors with whitespace in `hx-trigger`

src/htmx.js
In a SPA I am writing, I noticed that when adding an element with an indicator to the DOM, the indicator will "flash" (display for a brief moment). Specifically, in my case this is when content for a page is loaded via the "HX-Location" header.
I am not a CSS expert, but it appears as though the CSS transition is on the wrong element. Instead, the transition should be placed on the elements with opacity: 1 (when the request class is added).
I made that change locally in my app, and the "flashing" behavior went away. Here is a PR for that change.
=> fix indicator styles flash

src/ext/ws.js, test/ext/ws.js
Fixes #1930. 
When no sending element is provided to sendImmediately, the message is not sent to the socket, which contradicts the documentation which states that sendingElt is optional.
This PR:
- Fixes the issue
- Adds tests for correct current behavior of calling `beforeSend` and `afterSend` on the correct element if provided
- Adds a test that would previously have failed (doesn't send if no sendElt provided)
To the reviewers, I've noticed that no second level "describe" is used to group the tests. In order to better focus on my own tests, it was easier for me to have a sub section of tests under ws extension. I've left it as is but please let me know if that's an issue.
=> Fix WS sendImmediately

src/htmx.js
This is an attempt to address the situation where the `DOMContentLoaded` event has already fired, but `readyState` has not yet reached "complete" (for example it can be "interactive"). In this case initialization will never happen because `DOMContentLoaded` will never fire again. If we're looking for a "complete" ready state, the `DOMContentLoaded` event is irrelevant, we should be looking for ready state changes.
=> Fix for race condition in readystate detection

www/content/docs.md
Current version of the site has a weird heading on the section about hx-on, which is not only different from the rest, but also points to `#hyperscript` instead. This PR puts this in order
Also add `hx-on` to the table of contents in the docs
N/A
=> Fix hx-on anchor in the docs

www/content/docs.md
Fix invalid class name (in style tag) of request indicator .
=> Fix htmx-indicator example

src/htmx.d.ts
When playing around with View Transitions, I noticed that the `globalViewTransitions` property, as well as some other options, were missing from the `HtmxConfig` type. This PR aligns the `HtmkConfig` with the options listed on [htmx.org](https://htmx.org/reference/#config).
None
=> chore: add missing options to HtmxConfig type

www/content/docs.md
The [form example](https://htmx.org/docs/#validation-example) provided in the docs had 2 issues.
1. The custom validation message would not show on first submit because `reportValidity` wasn't called. Forcing the user to press a `submit` button 2x before seeing the message.
2. You couldn't submit the form after fixing the input because `setCustomValidity` was locked to the first error message. It needed to be cleared on `keyup`.
Tested on chrome and brave with a form / submit button on the form.
* [] I ran the test suite locally (`npm run test`) and verified that it succeeded
=> Fix form validation docs example

src/htmx.js
If I have following page:
```
<div hx-boost="true">
<a href="https://htmx.org/">asdasdasd</a>
</div>
<a href="https://www.google.com/">test</a>
... thousand of same link
<a href="https://www.google.com/">test</a> 
```
htmx on load will init all of the links on the page. However, it's necessary to init htmx only on one link inside hx-boost wrapper. This can result in poor performance on pages with lot of "plain" links.
Performance on page with 1K links (6 x slowdown):
Before:
After:
I have test the performance and simple boosted link.
approved via an issue - **I hope that it's bugfix**
=> Improve performance of lib during initialization phase

src/htmx.js
When specifying a `hx-trigger` attribute, `getTriggerSpecs` tokenizes & parses the trigger spec string everytime it's called.
This isn't an issue for most cases, but it performs poorly when operating on a large set of elements.
- In [this JSFiddle](https://jsfiddle.net/8fqzdyba/), using the current state of the lib _(open the developer console to see the logged execution times)_
I get in average the following:
```GetTriggerSpecs:  140 ms, called 2001 times```
- In [this JSFiddle](https://jsfiddle.net/wauz2f0g/) with the system I'm proposing here, I now get in average the following: 
```GetTriggerSpecs:  3 ms, called 2001 times```
The example code here is simply letting htmx initialize 2 000 divs, that have the exact same hx-trigger specified, which is in this example …
=> Cache evaluated trigger specs

src/ext/path-params.js, test/ext/path-params.js, test/index.html, www/content/extensions/_index.md, www/content/extensions/path-params.md
This PR adds an extension to use request parameters to populate path variables. Used parameters are removed so they won't be sent in the query string or body anymore. Unrecognised variables are just ignored leaving the placeholder as it is.
For example, this:
```html
<div hx-ext="path-params">
<a hx-get="/items/{itemId}" hx-vals='{"itemId": "42", "foo": "bar"}'>test</div>
</div>
```
would invoke the URL `/items/42?foo=bar`.
Motivation is mainly that it's more or less just an API design choice whether to use query parameters, path variables, or both. When the API is under your own control and a "backend for frontend" kind of an API not meant to be used in other ways, you can of course make the decision to use just query parameters. But when interacting with external or more general APIs …
=> add extension to populate path variables with request parameters

src/htmx.d.ts, src/htmx.js, test/attributes/hx-trigger.js, www/content/api.md, www/content/docs.md, www/content/reference.md
Following up on #1540
1) Indentation fix, as @1cg had suggested in the linked PR,
> is it possible to eliminate the whitespace changes here to make the actual change clearer and then submit a whitespace fix in a separate PR?
2) Added documentation & tests that I had omitted in the other PR
Added 2 tests
- One that evaluates the same trigger strings as the `parses spec strings` test, but enables the cache, and make sure the cache was indeed used, expecting it to hold the same keys count as the evaluated example specs list
- A second one that makes sure the cached specs are actually reused. It adds a dummy value to the evaluated specs, then evaluates trigger specs for a new element with the same trigger string, and makes sure the returned object is the same as the first one (i.e. was …
=> Trigger specs cache indentation fix + documentation & tests

src/htmx.js
I noticed that detached nodes accumulated in a project after multiple swaps. Memory heap snapshots contained detached elements with references to `htmx-internal-data` and a `replacedWith` property caused by this line:
Ref:
https://github.com/bigskysoftware/htmx/blob/206912b71d355477377aade60d06ea013c8e5455/src/htmx.js#L990
Important notes: 
* I do not understand the purpose of the `replacedWith`  property, there are no other references to it in the source code.
* I am also deleting the element's `htmx-internal-data` in `cleanUpElement()` because some elements would retain content in this structure (with references to elements no longer in the dom) _despite_ the preceding cleanup - I did not investigate why, or determine if there is ever a reason to retain data in `htmx-internal-data` when …
=> Prevent references to nodes swapped out of the dom accumulating as detached elements in memory

src/ext/sse.js, test/attributes/hx-sse.js, test/ext/sse.js, test/index.html
- Add: tests for the sse extension
- Partially Fix: `sse:*` inside of hx-trigger <sup>[(1)](#note-1)</sup>
- Fix: `sse-swap` events inside of previously swapped content
Previously `sse-swap` were only processed when `sse-connect` was on the root of what was being swapped in.
This is now fixed so that the closest sseEventSource is found and used as the event source.
While fixing this issue I ported the existing sse tests (`attributes/hx-sse.js`) to the sse extension, and while running those realized that the sse extension was not compliant with those tests, the change was one line so I decided to add it and make this a general sse extension fix pull request.
In some ways this is similar to the #1764 which seems to be stalled. However, it fixes a few more bugs, adds the missing testing. …
=> Fix: Make the SSE extension work properly and adhere to tests

src/ext/sse.js
There was a function naming conflict after #2025. I missed it because it worked on current dev since htmx.js initialized createEventSource parameter, but after removing it for 2.0, it led to infinite recursion and errors
Corresponding issue: discovered when updating #2095 to latest dev
I applied the patch to WS/SSE removal branch and ensured that recursion error was gone 
=> fix conflicting function names in sse.js

src/htmx.js, test/core/shadowdom.js, test/index.html
Adds basic support for using HTMX inside of shadow DOM. HTMX attributes will not be automatically sought out inside of shadow roots, but can be enabled by calling `htmx.process(elt.shadowRoot)` on desired elements. All basic functionality should work, and will treat the containing shadow root as if it were the entire document unless otherwise specified.
This also expands the extended selector syntax used by `hx-target` et al. to include two new options:
- `root` - the current shadow root, or `document` if not applicable.
- `global <extended selector>` - selects from `document` rather than the current shadow root.
Note that this is not a fully tested feature; for example, I anticipate history support potentially running into issues with it. However, per 1cg's instructions, these issues …
=> Add support for shadow DOM

src/htmx.js, test/manual/hxboost_partial_template_parsing/index-partial.html, test/manual/hxboost_partial_template_parsing/index.html, test/manual/hxboost_partial_template_parsing/other-content.html, test/manual/index.html
**This PR:**
* Fix the duplication of head's children tags inside the content when parsing fragments regardless of the status of `useTemplateFragments` configuration.
* These modifications are applied for both parsers: template fragment and plain HTML (default). The new strategy is to skip head tag parsing on the `makeFragment(response)` function as head-support extension already implemented a proper merging algorithm for that.
* Added a manual .html test: `hxboost_partial_template_parsing/index.html, index-partial.html & other-content.html`.
* Also added an array with similar regular expressions to be compiled only once and not for every execution (**edit:** replaced the array approach by constants).
**Corresponding issue:** https://github.com/bigskysoftware/htmx/issues/2018
**This PR …
=> Improve head tag parsing on template fragments

src/htmx.js
I modified the HX-Retarget header handling to use extended css selectors.
#1962 
I made a quick webserver and html site using golang echo.
```go
package main
import (
"github.com/labstack/echo/v4"
)
func main() {
e := echo.New()
e.GET("/", func(c echo.Context) error {
return c.File("idx.html")
})
e.GET("/htmx", func(c echo.Context) error {
return c.File("../../htmx/src/htmx.js")
})
e.POST("/changethis", func(c echo.Context) error {
c.Response().Header().Add("HX-Retarget", "this")
return c.String(200, "changed")
})
e.POST("/changehi", func(c echo.Context) error {
c.Response().Header().Add("HX-Retarget", "#hi")
return c.String(200, "bye")
})
e.POST("/changepreviousp", func(c echo.Context) error {
c.Response().Header().Add("HX-Retarget", "previous p")
return …
```
=> rewrite the HX-Retarget header to use extended query selectors

src/htmx.js, test/attributes/hx-swap.js, test/attributes/hx-trigger.js, test/core/internals.js
When a parameter like "0ms" is passed in to parseInterval it gets parsed to 0. Previously this would result in a return value of "undefined" because 0 is falsy and thus the `return 0 || undefined` statements return undefined.
The purpose of the form `parseFloat(str) || undefined` was to return "undefined" if parseFloat failed (parseFloat returns NaN, a falsy value, if it can't parse its argument). Unfortunately, as mentioned, parseFloat can also succeed and return a falsy value -- when the argument is "0" (or "0.0", etc.). So the new code, rather than depending on the falsiness of the result of parseFloat, explicitly checks for a NaN.
=> Update parseInterval to handle "0" correctly

www/content/attributes/hx-swap-oob.md, www/content/docs.md
3 years ago, @1cg pushed [this commit](https://github.com/bigskysoftware/htmx/commit/b96e5e771ef83d284af6a5fdd11a2c37abc855f9)
> allow `hx-swap-oob` to be at any level in returned content
Yet 3 years later, the [hx-swap-oob](https://htmx.org/attributes/hx-swap-oob/) documentation still states the following:
> Out of band elements must be in the top level of the response, and not children of the top level elements.
which doesn't seem to be true anymore, given that the commit mentioned above introduced a [test case](https://github.com/bigskysoftware/htmx/commit/b96e5e771ef83d284af6a5fdd11a2c37abc855f9#diff-7089bd70f59ce011095405d0fa57ee13073d0a8317209d95a9a26f353abaff36R73) for the nested elements scenario.
_Btw, this also seems to make the `multi-swap` extension kinda obsolete now as its …
=> Removed outdated note in oob swap documentation

src/htmx.js, test/attributes/hx-swap-oob.js, www/content/attributes/hx-swap-oob.md
As discussed in the Discord, here's a template-based suggestion to work around the annoying scenario of oob-swapping the lone `tr` or `td` to, which by default won't work if there are any elements before it in the response, because of the way the DOM parser works.
Updated the docs to mention that scenario and the way we would now recommend to address it.
=> Support encapsulating oob swap elements in templates in response

.github/workflows/ci.yml
So we can spot mistakes during htmx2 development too
=> Enable Node CI for v2.0v2.0 branch

www/content/extensions/path-params.md
The `path-params` doc didn't have quotes around its title, resulting in the following error when attempting to execute `zola serve` to run the htmx website locally
```
Building site...
Error: Failed to serve the site
Error: Error when parsing front matter of section `\\?\D:\workspace\git\htmx\www\content\extensions\path-params.md`        
Error: Reason: TOML parse error at line 2, column 9
|
2 | title = path-params
|         ^
invalid string
expected `"`, `'`
```
=> Fix path-params title (preventing zola from building)

www/content/essays/why-tend-not-to-use-content-negotiation.md
=> Fix broken link in essay

www/content/docs.md
Fixes typo in `dahs` to `dash` in `content/docs.md`
NA.
NA.
=> typo: dahs -> dash

src/htmx.d.ts
This adds more type-safety to extension developers, since the event name in `onEvent` is now no longer of type `string`, but uses a. new union-type of all available event names as string.
The type and the available events are based on [what's written in the docs](https://htmx.org/reference/#events).
Corresponding issue: _there is no issue atm. please let me know when I should create one._
This only changes the type definition, not the actual source-code, therefore no tests are provided.
=> Add TypeScript union string type for custom event names

src/htmx.d.ts
I updated the type signature of `htmx.ajax` to allow the user to not provide a value to the `element` argument and just use the default documented value, `body`.
=> Update `htmx.ajax` type signature to make the `element` argument optional

www/content/essays/is-htmx-another-javascript-framework.md
=> Fix typo in framework essay

www/content/extensions/client-side-templates.md
I don't know why this was in here in the first place, it's just outright false. Neither Mustache nor the CST extension have any sort of code to enable using `<script type="text/mustache">` like this. The `<object>`-based example for XSLT templates should probably be double-checked too.
Removed erroneous text from https://htmx.org/extensions/client-side-templates/
=> Remove incorrect external script info from client-side-templates docs

www/content/examples/tabs-javascript.md
Fix typo in tabs-hyperscript by making the `aria-controls` property of the tabs (buttons) point to `<div id="tab-contents" ...>`
https://github.com/bigskysoftware/htmx/issues/2163
(not applicable)
=> Fix typo in Hyperscript Tabs docs

src/ext/sse.js, test/attributes/hx-sse.js, test/ext/sse.js
I'm building a toy chat app with HTMX + the SSE extension. I have some custom JS that I want to run **before and after** new SSE messages are swapped in from the server.
For a regular request with HTMX, I could add listeners to the `htmx:beforeSwap` and `htmx:afterSwap` events. Similarly, the WS extension emits `htmx:wsBeforeMessage` and `htmx:wsAfterMessage`, but there is no corresponding ability to listen to "before swap" messages with the SSE extension.
This PR introduces a new event, `htmx:sseBeforeMessage`, that is emitted before the SSE extension swaps in content from the server. Open to feedback on naming convention!
I tested this change manually by applying this patch to my local copy of the SSE extension.
=> Fix SSE tests and emit new "beforeMessage" event for SSE Extension

www/templates/shortcodes/demoenv.html
This PR resolves #2189 
Fixes a small visual bug on the docs site where list items in the demo-server-info panel overflow are cut off because they overflow past the edge of the viewport.
Before fix:
After fix:
Again, (as I mentioned in #2188), apologies if I'm jumping the gun by sending this PR before explicit approval of the associated issue. This was also a one-line CSS fix, so I thought it wouldn't hurt to just send in a PR at the same time as the issue.
=> [Website]: Fix cut off list items in demo-server-info panel

www/templates/shortcodes/demoenv.html
This PR resolves #2187 
Fixes a tiny visual bug on the docs website where the demo-server-info panel is not rendering above some example page content (namely the link emoji).
Before fix:
After fix:
Also, apologies if I'm jumping the gun by sending this PR before explicit approval of the issue I submitted. Since this was a one-line CSS fix, I thought it wouldn't hurt to just send in a PR at the same time as the issue. 
If, in the future, you would like me to wait for explicit approval please let me know 😊
=> [Website]: Fix demo-server-info panel rendering issue

.github/workflows/ci.yml
Upgrade these github actions to v4:
- checkout
- setup-node
=> chore: upgrade actions to v4

www/content/attributes/hx-validate.md
Fixes #2185
The [hx-validate](https://htmx.org/attributes/hx-validate/) documentation says "Form elements do this by default, but other elements do not" which is quite confusing, I interpreted this to also mean `<input>` elements validate by default. This PR solves that confusion and also makes it clear that hx-validate must be set to "true".   
This change has not been explicitly approved by the maintainers via the issue, hope that's ok. If not, please let me know and I won't make a PR next time until it's approved. 
Corresponding issue: #2185 
=> Clarify hx-validate documentation

www/content/essays/is-htmx-another-javascript-framework.md
Trivial removal of typo.
https://github.com/bigskysoftware/htmx/issues/2181
N/A, I think.  It's a change to one of the essays.
=> Remove extraneous `to` from essay (is-htmx-another-javascript-framework.md)

test/index.html
When trying to contribute, [docs suggest](https://github.com/bigskysoftware/htmx/?tab=readme-ov-file#hacking-guide) to use `npx serve` and then go to http://0.0.0.0:3000/test/ to see all tests, in this file there's a link to the manual tests, but if you have followed the steps on the guide you will realize that the links for the individual manual tests are not working, all files will throw a 404, the first time I saw this I didn't know if I had something misconfigured, then I realized that the links were relative and since the link to "manual" didn't have a trailing slash, all individual manual tests were pointed to the root of tests folder (i.e. `http://localhost:3000/test/aborting-request` instead of `http://localhost:3000/test/manual/aborting-request`)
The "correct" way to fix this …
=> Add trailing slash to manual tests link

www/content/server-examples.md
Documentation update only - Added Scala (http4s) example to server examples page.
website checked locally with Zola
=> Add Scala http4s example to docs (server-examples)

www/content/attributes/hx-boost.md
This note would have really helped me when I was working on avoiding my maplibre canvas div from being overwritten when using hx-boost. I was initially confused by the hx-boost=false note thinking that is what I needed.
This is untested.
=> www: mention hx-preserve on hx-boost

www/content/examples/bulk-update.md
Use ARIA to announce a summary of the bulk update. By using a checkbox input to represent the activation status, we don't need to re-render it when it's changed, because the checkbox itself manages that state.
Corresponding issue: #1431
Tested manually by running Zola locally, verified behaviour works as intended.
=> Minimize re-rendering of 'bulk update users' table

www/content/examples/value-select.md
Code examples does not include element with class `.htmx-indicator` used for hx-indicator attribute
=> Show element used for hx-indicator in value-select example code

www/content/reference.md
Before / After
* Brought many of the descriptions down to a single line while improving consistency.
* Moved `hx-boost` to Additional Attribute Reference to prevent learners from getting sidetracked.
* Clarified language for `hx-select-oob` vs `hx-swap-oob`.
* Fixed: "handle events with a inline scripts on elements" -> "handle events with inline scripts on elements"
=> Docs: Reference page. Shortened, clarity.

www/content/examples/_index.md, www/content/examples/web-components.md
Added an example explaining how to integrate HTMX with web components and shadow DOM.
=> Add web components / shadow DOM example to docs

www/content/docs.md
Before / After
Reduced wordiness.
=> Docs: Less wordy client scripting introduction.

www/content/migration-guide-hotwire-turbo.md
* New examples for `hx-on` !
* Clarified `hx-boost` commentary.
* Turbo Streams vs Turbo Frames vs htmx commentary.
=> Docs: Hotwire migration guide: Examples for hx-on! Turbo Streams commentary.

www/content/extensions/server-sent-events.md
Fixes #2197
Adds a reference to `hx-swap` from the SSE extension doc page.
#2197
N/A
=> [DOC] Adds a reference to `hx-swap` from SSE extension

www/content/examples/bulk-update.md
Show hx attributes used in bulk-update code example.
These are only visible in the `displayUI` function when reviewing the raw file  
=> Show hx attributes used in bulk-update code example

jsconfig.json, package-lock.json, package.json, src/htmx.d.ts, src/htmx.js
- Added JSDoc basically everywhere
- Used parent types whenever possible _(i.e. Node instead of Element, Element instead of HTMLElement and so on)_
- Typescript types definition is now generated, using `npm run type-declarations`
- Inlined public API's functions within the `htmx` object itself as `tsc` would otherwise generate invalid TypeScript code
- I put all custom `typedef`s in the global scope so that `tsc` properly exports them, and at the bottom of the file as I thought it would be pretty annoying to have to scroll past 150~ lines of JSDoc to start reading the code
- To avoid making _too many_ changes to the code, I added a few `// @ts-ignore` in places where code _is_ valid but tsc is too strict
Tests pass, also ran the tests in the extensions repo, all clear
If this is accepted, …
=> JSdoc in htmx.js + generated TypeScript definition

src/ext/sse.js, test/ext/sse.js
Currently when EventSource loses connection with the server, e.g. when server restarts and later SSE ext reconnects it creates new EventSource, but is not adding any previously registered listeners. As a result while server issues new events, SSE ext no longer consumes them.
Refs: #2225
Tested on a real application by using the exact changes and patching the npm package with `patch-package` module first.
All the existing tests are passing:
approved via …
=> SSE Ext #2225: reinstantiate EventSource listeners upon reconnection logic

src/htmx.js, test/attributes/hx-swap.js, www/content/attributes/hx-swap.md
I added a new swap style called `textContent` that does text-content swaps. This swap style treats the response content as plain text to prevent XSS attacks.
I added four new tests.
=> Add textContent swap style

www/content/webring.md
Adds [Recipya](https://recipes.musicavis.ca) to the webring.
Source code: https://github.com/reaper47/recipya
Where htmx is used: https://github.com/reaper47/recipya/tree/main/web/components
N/A
N/A: change to just the website
=> Add Recipya to the webring

www/content/extensions/server-sent-events.md
The SSE extension docs suggest that `hx-swap` works, which it sort of does, except that (as noted in #784) the modifier functionality documented on the `hx-swap` attribute is silently ignored.
Corresponding issue: #784
(I'm not a node developer and don't have all the dependencies to run the test suite -- if you're concerned that this Markdown wording change might have broken the tests, lmk and I can look into it.)
=> [DOC] clarify SSE hx-swap docs to note #784

src/htmx.js, test/attributes/hx-swap-oob.js, www/content/attributes/hx-swap-oob.md, www/content/docs.md, www/content/reference.md
This adds a new configuration option, `allowNestedOobSwaps`, which preserves existing behavior when set to the default `true`, but when set to `false` it changes `handleOutOfBandSwaps` to only process elements with `hx-swap-oob` and `data-hx-swap-oob` that appear at the *root* of the response fragment, i.e. elements whose parent element is `body`. Elements deeper in the dom tree fragment are ignored and the `oob-swap` attribute is stripped instead.
> The current system means you can just randomly intersperse oob fragments anywhere within the main response and they are swapped in from wherever to wherever. It seems much more conceptually sound to require all oob-swaps to originate adjacent to the response's main element.
Enabling this configuration option is helpful when you want to reuse …
=> Add config option to ignore nested oob-swaps instead of processing them

src/htmx.d.ts
This PR fixes the TypeScript types in `src/htmx.d.ts`. There were two separate issues:
- Line 432 contained invalid syntax.
- `triggerSpecsCache` referenced a `HtmxTriggerSpecification` type the doesn't exist
Given the guidance in https://github.com/bigskysoftware/htmx/pull/2107#issuecomment-1866499625, I opted to remove the types for `triggerSpecCache` entirely.
Interestingly, there are other parts of the code (JSDoc comments) that reference `HtmxTriggerSpecification`:
- https://github.com/bigskysoftware/htmx/blob/7f3d114269d423ac8e77c64e988d6f4cf60325b1/src/htmx.js#L1273
- https://github.com/bigskysoftware/htmx/blob/7f3d114269d423ac8e77c64e988d6f4cf60325b1/src/htmx.js#L1364
This leads me to believe that this type did exist at one point, but I couldn't immediately find it in the Git …
=> Fix TypeScript types

test/core/regressions.js
Just added 2 tests to confirm the htmx 2 issue we had identified with double script execution, also happens on htmx 1
See #2030
Only happens with `htmx.config.useTemplateFragments` set to true
=> Double script exec tests variants using templates: issue confirmed

src/ext/sse.js, src/ext/ws.js
Seems like Safari on iOS 17.4 doesn't correctly set `event.target` from custom events dispatched from JS. Earlier same issue occurred in my htmx-signalr extension: https://github.com/Renerick/htmx-signalr/pull/11
Corresponding issue: https://discord.com/channels/725789699527933952/1216185723229704222
I've ran the test suite and verified that test server still works. However, I don't have iOS 17.4 device at hand, so will have to ask the user to verify if it works.
=> WS.js fix for Safari on iOS 17.4

www/content/attributes/hx-disabled-elt.md
This update clarifies the hx-disabled-elt attribute's ability to accept multiple CSS selectors, separated by commas, enabling developers to disable multiple elements simultaneously during an HTTP request.
=> Add documentation for multiple CSS selectors in hx-disabled-elt

src/htmx.js, test/core/ajax.js, test/core/regressions.js
Fixes some IE11 incompatibilities
- default parameter value in `function makeTagRegEx(tag, global = false)`, [not supported by IE11](https://caniuse.com/mdn-javascript_functions_default_parameters)
- string literals in that same function, [not supported by IE11](https://caniuse.com/template-literals) either
- the test utility functions call `htmx.processNode` on text nodes (i.e. not actual `Element`s). This fails gracefully on modern browsers but not so gracefully on IE11. Added 2 checks in hx-on processing functions, to avoid calling undefined references (a text node doesn't have `.attributes` neither `getElementsByTagName`)
- some tests cannot work on IE11 (unsupported features) but were simply not skipped, fixed that
See #1687 with the procedure to run tests on …
=> Fix IE11 incompatibilities

www/content/docs.md
In the Animations section of the documentation, I had expected that the link labeled "CSS Transitions" would jump me to the CSS Transitions section. Instead it redirected me to a Mozilla webpage which was unexpected.
=> Link to section on CSS Transitions instead of Mozilla page

www/content/extensions/client-side-templates.md
The unnecessary escape sequences were removed from the [mustache full example](https://htmx.org/extensions/client-side-templates/#full-mustache-html-example) as they broke the output.
The template key "UserID" was renamed to "UserId" as the [test API](https://jsonplaceholder.typicode.com/todos/1) uses "UserId". The old key name would result in a blank string as the keys wouldnt match.
https://github.com/bigskysoftware/htmx/issues/2407
I have tested the changed example in the docs. It is working correctly.
=> Fix example for mustache in client-side-templates extension.

src/htmx.js
In a `multipart/form-data` form, current implementation with the proxied FormData results in requests being malformed (wrong content type set to `text/plain`, FormData sent as `[object FormData]` in the payload)
Couldn't get the proxy object to work properly with XMLHTTPRequest's `send` method; even though calls are being forwarded to the underlying FormData through the proxy, the request won't set its type to `multipart/form-data` when appropriate and instead send a `text/plain` request.
One simple fix/workaround here is to copy the values into a new, actual FormData (not a proxied one)
#2317 
Also see [this JSFiddle](https://jsfiddle.net/ftksy2wu/) to reproduce the issue
Didn't know how to add a reliable test for this tbh, given that we mock the requests in our test …
=> Fix #2317 force conversion to FormData for xhr.send

www/content/webring.md
Adds [Statusnook](https://statusnook.com) to the webring.
Source code: https://github.com/goksan/statusnook
N/A
N/A
=> Add Statusnook to the webring

README.md
_Disclaimer: targeting dev as htmx 2 isn't on master yet and htmx 1 still requires Node 15._
As per #2122, one may now use Node 20 or even 18, we finally don't require Node 15 specifically anymore,
=> Remove Node 15 requirement mention from README

www/content/docs.md
Noticed a few missing apostrophes when reading through the docs. Figured I'd be a good citizen. 
I did no testing as it appears none is needed. 
- I tried but I do not use Chrome.
=> fix(docs): Add missing apostrophes

www/content/examples/tabs-hateoas.md
The `aria-selected` attribute should be set to true in the first tab for consistency with the class `selected` being set.
=> docs: aria-selected true in Tabs HATEOS example

www/content/examples/confirm.md
Update the `.then()` handler in the `onClick` attribute to use an arrow function instead of a traditional `function(arg)` expression. 
The `window` scope was being accessed instead of the intended `button`.
This fixes the `this` binding within the lexical scope, ensuring that `this` is bound to the `button` instead of the `window` and resolving the issue.
Corresponding issue: #2257 
The GIF demonstrates that clicking the button logs `this` to the console. The change ensures correct `this` …
=> docs: fix `this` binding in `onClick .then` handler with arrow function

src/htmx.d.ts, src/htmx.js
This PR improves htmx extension registration by allowing extensions to contribute to the selector used in `findElementsToProcess`. This change makes extension initialization much simpler since it can just inform htmx about what elements it want to process without the need to look for them in processed fragments. This change nicely avoids double processing issue since deduplication logic is implemeted by `querySelectorAll` 
Corresponding issue: bigskysoftware/htmx-extensions#16
Since 2.0 repo has no extension, tests for this behavior are added to corresponding extension directory over at bigskysoftware/htmx-extensions
see https://github.com/bigskysoftware/htmx-extensions/pull/18
=> [2.0] Improve extension registration logic

www/content/talk/index.md
The old url doesn't work, this replaces it with one that does work.
Alternatively, if you would like to embed the graph in the page, you can use the following markdown.
```
[![Star History Chart](https://api.star-history.com/svg?repos=bigskysoftware/htmx&type=Date)](https://star-history.com/#bigskysoftware/htmx&Date)
```
[![Star History Chart](https://api.star-history.com/svg?repos=bigskysoftware/htmx&type=Date)](https://star-history.com/#bigskysoftware/htmx&Date)
=> (website) Fix url to github stars

www/content/_index.md, www/content/examples/animations.md, www/content/examples/bulk-update.md, www/content/examples/click-to-edit.md, www/content/examples/click-to-load.md, www/content/examples/delete-row.md, www/content/examples/dialogs.md, www/content/examples/edit-row.md, www/content/examples/inline-validation.md, www/content/examples/keyboard-shortcuts.md, www/content/examples/modal-bootstrap.md, www/content/examples/modal-custom.md, www/content/examples/progress-bar.md, www/content/examples/tabs-hateoas.md, www/content/examples/tabs-javascript.md, www/templates/shortcodes/demoenv.html, www/themes/htmx-theme/static/css/site.css
Followup PR for #2562 with fixes to dark mode styling, mostly in Examples:
- missing `btn-danger` class fixed
- corrected usage of `btn-primary` to `primary` class
- added dark mode styles for buttons in general
- applied `btn primary`/`btn danger` classes to buttons that had no styling until now
- added dark mode styles for the server requests bottom drawer in Examples
- fixed styles for tabs examples in dark mode
Locally via Zola
=> Dark mode fixes

www/content/docs.md
Fix 3rd party library name in documentation (https://htmx.org/docs/#undoing-dom-mutations-by-3rd-party-libraries)
=> fix 3rd party lib name in example doc

www/content/_index.md
=> _index.md: remove malformed html fragment in sponsors table

www/content/reference.md
This PR fixes the link to the `hx-inherit` page from the reference page in the docs.
=> Docs: Fix reference link to `hx-inherit`

www/content/examples/update-other-content.md
Fix a document in response payload in [update-other-content](https://htmx.org/examples/update-other-content/#oob) page regarding oob
Website change. No test. build is successful
=> docs: fix incorrect payload in update-other-content oob page

www/themes/htmx-theme/static/css/site.css, www/themes/htmx-theme/templates/base.html
For wider screens the documentation and its content is too narrow. This will add more breakpoints (inspired by Tailwind's breakpoints) to /docs, but leave narrow column for other pages.
Corresponding issue: #2633 
Visually with Zola
=> Make docs' content responsively wider

www/content/attributes/hx-disabled-elt.md
I've also updated the example to disable inner form fields only
=> Docs: Mention all extended selector keywords in `hx-disabled-elt` docs

www/content/events.md
Updated oobBeforeSwap since it's out of date for two reasons:
- `shouldSwap` always defaults to true
- `xhr` and `requestConfig` are not properties of `detail`
- `fragment` is not documented
Regarding the `shouldSwap`, I've run tests returning 300 status codes and they did not set the `shouldSwap` property to false, as was previously specified. I've also reviewed the [source code](https://github.com/bigskysoftware/htmx/blob/f9b3f883576c979b533ed657b8a7556c3b1982e4/src/htmx.js#L2933) with a debugger to ensure that the `shouldSwap` in fact never changes and is always true unless modified by the event listener.
=> Doc: Update oobBeforeSwap

www/content/events.md
This PR reverts the incorrect removal of `detail.elt` from the `htmx:oobAfterSwap` and `htmx:oobBeforeSwap` events.
=> Docs: Revert `detail.elt`

www/content/attributes/hx-get.md
Added a note in the `hx-get` attribute file to convey the implications of an empty request
#2623 
Visually
=> Update in Documentation

src/htmx.d.ts, src/htmx.js, www/content/api.md
The typedef is currently more strict than the code, and prevents IMHO the most useful way to configure ajax requests.
I also added a clarification to the `htmx.ajax` docs about what specifying `source` in the context object actually does.
See discussion here:
https://github.com/bigskysoftware/htmx/discussions/2698
...oh, do the docs and code changes need to be in separate PRs?
=> HtmxAjaxHelperContext typedef should have all optional fields

www/content/server-examples.md
Make sure Quarkus is referenced with recent examples in the htmx ecosystem
Corresponding issue: https://github.com/quarkusio/quarkus/issues/41540
no test needed because it's just update the examples on www
* [x ] I have read the contribution guidelines
* [x ] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
* [x ] This is either a bugfix, a documentation update, or a new feature that has been explicitly
=> #41540 Update Quarkus with recent examples

www/config.toml, www/content/attributes/hx-trigger.md, www/content/docs.md
Make some small tweaks to the docs to mention that hx-trigger:from doesn't update when the page changes.
Fixes #2689 , and gives an example from there.
I also fixed a typo in www/config.toml. This was actually a typo in zola, reported in https://github.com/getzola/zola/issues/2537 and fixed in the latest release. I can take this out if you want to stick to an older version of zola.
=> Clarify that hx-trigger:from doesn't dynamically update

src/htmx.js
I introduced an additional check `template.content.textContent.trim() === ''` to make sure templates are not removed if they have plaintext inside.
#2702 
I ran the sample server.py code provided by the person opening the PR. I then changed the source to htmx to my localhost htmx src. I added the additional check in the if statement and refreshed a few times.
**Without my change:**
with plaintext:
without plaintext:
**With my change:**
with plaintext:
without …
=> Let templates have plaintext as contents (fixes 2702)

src/htmx.d.ts, src/htmx.js
The @see tag prevented `tsc` to properly generate types for `HtmxExtension`. Moving the `@see` above `@typedef` fixes this and adds types for `HtmxExtension` back to the package ;-)
https://github.com/bigskysoftware/htmx/pull/2336 updated type generation but as a side effect the type definition of `HtmxExtension` got dropped / changed to `any`. 
This is fixed now ;) 
Note: I did not create an issue to prevent spam, if it's important, I'm more than happy to create one after the fact 😉
=> fix: type definitions for HtmxExtension

www/themes/htmx-theme/static/css/site.css
Docs page's nav items contain hierarchical indentation for headings that doesn't work well when text is aligned center on small screen. This PR removes the responsible text-align style to keep the nav items left-aligned on small screen. The changed style also matches the current style on larger screen.
See the following images for comparison:
| Before | After |
| -- | -- |
| ![image](https://github.com/user-attachments/assets/0c4492d1-6d80-45ce-8160-3dc066c5df19) | ![image](https://github.com/user-attachments/assets/ecace927-dd01-4c4d-9e9a-02ac0d4c5dda) |
The change in this PR should not affect the style for any other part of the website since CSS `.nav` …
=> Stop center aligning docs nav on small screen

netlify.toml
The current website build uses Zola 0.17.1, and is not generating `atom.xml`. Building the site with version 0.19.1 does generate this file (at least locally). This PR bumps the version in the Netlify config file.
Corresponding issue: N/A _(Discord ping)_
[Zola's Netlify deployment docs](https://www.getzola.org/documentation/deployment/netlify/) say that any valid version will work in this config.
=> Bump Zola version to 0.19.1

src/htmx.js, test/core/parameters.js
Former implementation of `overrideFormData` was overriding all values for a given key, one key after the other, thus breaking the initial order of values.
This situation wasn't caught by existing tests (see 01b292ada48f31276642b587eb67128367349701), as the tested case was a `GET` request, for which we don't run the values override with the closest form's values.
This PR fixes #2703 by overriding values in order using `forEach` on the `FormData`, ensuring to preserve the initial order
Corresponding issue: #2703
Added a test case for a `POST` request as well
=> Fix: values order with non-GET requests

src/htmx.js
Current implementation of FormData proxy fails to encode objects, which are appended as a poorly-stringified version, aka `'[object Object]'` (the `toString` equivalent).
This PR fixes this by calling `JSON.stringify` on such objects
Corresponding issue: #2616
- Current situation can be tested on [this JSFiddle](https://jsfiddle.net/g9yq8f7h/1/), notice how the `foo` param is incorrectly formatted
- Fix with this PR can be tested on [this JSFiddle](https://jsfiddle.net/g9yq8f7h/2/), notice how the `foo` param is now correctly formatted
=> Fix: stringify objects when appending them to FormData

src/htmx.js, test/core/headers.js, www/content/headers/hx-trigger.md
This PR adds the ability to trigger an event on another element using the [`HX-Trigger`](https://htmx.org/headers/hx-trigger/) response header (also `HX-Trigger-After-Swap` and `HX-Trigger-After-Settle`) by allowing a `target` argument.
```
HX-Trigger: {"myEvent": {"target": "#myElement"}}
```
Added a test to ensure the event is triggered on the `target` element.
=> Add ability to trigger an event on another element using `HX-Trigger` response header

www/content/reference.md
=> Fix inlineStyleNonce typo in reference

src/htmx.js, test/core/parameters.js
Fixes #2630
When converting an object to FormData, we had a simple check that if a value was an object, we'd JSON-stringify it before appending it to the FormData.
#2748 addressed a _similar_ issue, thoughI had totally missed that a similar check was done elsewhere in the code.
One case was not handled here, causing the referenced issue ; the `Blob` type, that `FormData` can perfectly handle _(a type that includes `File`s)_, would be JSON-stringified instead of directly passed to `FormData.append` as it's an `object` itself, resulting in the loss of the file data, and that conversion to an empty object.
Corresponding issue: #2630
Added a test cases, to ensure that `htmx.ajax` with a file passed in parameters, is correctly uploaded and not empty.
Also added another test case with a file …
=> Fix file upload through htmx.ajax

src/htmx.js, test/attributes/hx-boost.js
Boosting forms with method="dialog" should not trigger AJAX requests because these are only meant to close parent `<dialog>`  elements and not submit anything.
> When a `<form>` within a `<dialog>` is submitted via the dialog method, the dialog box closes, the states of the form controls are saved but not submitted
source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#usage_notes
Can be tested with the following snippet:
```html
<body hx-boost="true">
<dialog id="modal">
<form method="dialog">
<button>Close modal</button>
</form>
</dialog>
</body>
<script type="text/javascript">
document.getElementById("modal").showModal()
</script>
```
Clicking the "Close modal" button should not trigger any AJAX requests
=> Do not boost forms with method="dialog"

www/content/docs.md
In the docs, the following example is given to configure response handling via the `<meta>` tag:
```html
<meta name="htmx-config" content='{code:"204", swap: false},   // 204 - No Content by default does nothing, but is not an error
{code:"[23]..", swap: true}, // 200 & 300 responses are non-errors and are swapped
{code:"422", swap: true}, // 422 responses are swapped
{code:"[45]..", swap: false, error:true}, // 400 & 500 responses are not swapped and are errors'>
```
However, if this is used in a site which loads [htmx v0.2.0](https://unpkg.com/htmx.org@2.0.0/dist/htmx.js), the following error is thrown:
```
htmx.js:2914 SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2)
at JSON.parse (<anonymous>)
at parseJSON (htmx.js:816:19)
at getMetaConfig …
```
=> Fix example for responseHandling config via <meta> tag

src/htmx.js, test/attributes/hx-trigger.js
`hx-trigger` with delay modifier did not fire `htmx:trigger` event. This behavior was inconsistent with plain(non-delay) events.
Demo: https://jsfiddle.net/yu59noed/
Added test case for delayed htmx:trigger. This test case failed on current dev branch.
=> fix: Fire htmx:trigger event on delayed triggers

CONTRIBUTING.md
Excited to see this unframework framework as a long time (since 1998 coder) HTML appreciator. 
I wanted to learn about extensions but noticed a broken link that others might stumble upon. 
Consider rephrasing a question to invite a person to contribute their issue. (this can be ignored if you like).
=> Update CONTRIBUTING.md  - fixing a link, wording

www/content/docs.md
These are the changes that I forgot to include in https://github.com/bigskysoftware/htmx/pull/2715 based on feedback in the comments.
Corresponding ~issue~ PR: https://github.com/bigskysoftware/htmx/pull/2715
/cc  @alexpetros (as requested in https://github.com/bigskysoftware/htmx/pull/2715#issuecomment-2269835949)
Made sure config is valid JSON. Rest was already tested in https://github.com/bigskysoftware/htmx/pull/2715.
=> Add HTML comment and catch-all to responseHandling config via <meta> tag

www/content/docs.md
Update the link in the “installing” section to point to v2. The other installation methods link to version 2, but this one didn’t.
Corresponding issue: n/a
Opened link.
=> Update installing download link to v2

www/content/docs.md
unminified cdn link has missing . and should be 2.0.2 not 2.02
#2812
Tested cdn link was broken but worked in a project fine with updated link
=> fix cdn typo

www/content/docs.md
one of the responseHandling examples has invalid js code which needs to be a JSON string format and its missing the root responseHandling node. and comments can't be in json.
Tested new meta tag to make sure it works as expected when used in a header.
=> fix responseHandling meta example

test/core/ajax.js, test/core/validation.js
Added a basic test for radio input form submission, following the example for checkbox inputs.
Added tests for custom validation on radio and checkbox inputs when the inputs are empty, to support things like 'you must choose an option from at least one of these groups' etc.
These tests pass for v2 due to the refactoring of `processInputValue` in commit `b9322450ff42a5bdf25b194fcdb6ecc744353819` : https://github.com/bigskysoftware/htmx/commit/b9322450ff42a5bdf25b194fcdb6ecc744353819#diff-f14ff7f8c91a6f76e7688c45ca01d600e8928769b268caa71cf09b8f12661f3dR2528-R2530
- however, it's not totally obvious reading that code why there are now two separate calls to `validateElement` under different conditions, so while I'll submit the main bugfix for https://github.com/bigskysoftware/htmx/issues/2676 …
=> Issue #2676 - Tests for v2 to prevent regression of issue from v1

www/content/docs.md
Add a link, as exists for `htmx:responseError` above.
Corresponding issue: n/a
=> Link to htmx:sendError from error description

www/content/docs.md
=> Fix duplicate typo

www/content/extensions/_index.md
As we moved extensions to a separate repository and removed docs from the main website, the https://htmx.org/extensions page that used to display the extensions documentation, now results in a 404,
As @alexpetros suggested, this isn't ideal and should at least redirect to the new extensions website.
Related issue: #2813
=> Redirect /extensions to extensions website

src/htmx.js, test/core/events.js, www/content/api.md
This PR adds the ability to add an `options` (or `useCapture`) argument to the event listener when using `htmx.on()`.
As per the [`addEventListener()`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) method spec, the third argument accepts an [`options`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#options) object or a [`useCapture`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#usecapture) boolean.
Usage:
```js
// Using an object
htmx.on('htmx:afterSwap', () => console.log('Swapped'), { once: true }); 
htmx.on('#my-div', 'htmx:afterSwap', () => console.log('Swapped'), { once: true });
// Using a boolean
htmx.on('htmx:afterSwap', () => console.log('Swapped'), true); 
htmx.on('#my-div', …
```
=> Ability to add `options` argument to event listener

src/htmx.js
It is possible that element can be revealed not only because of scroll but because window size is changed or other elements in a page dynamically changed.
1. Load test page in small window with test element (activated by hx-trigger="revealed") below visible area.
2. Resize the window.
3. When test element is visible revealed event is missing.
* [yep] I have read the contribution guidelines
* [dev] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
* [fix] This is either a bugfix, a documentation update, or a new feature that has been explicitly
=> Listen to resize events and check revealed

test/core/parameters.js
Even though we call `.focus` on elements in these 2 tests, the `focusin` event _might_ not be fired.
Disclaimer: the CI suddenly constantly fails on this, and I have no idea why, specifically why it worked until now and suddenly doesn't anymore.
To reproduce that issue, run the tests locally through `npx serve` (thus browser context) with a `20x CPU slowdown` throttling. Refresh the tests page, and click outside it **before** these tests run.
Adding logs reveal that, even though the `document.activeElement` gets properly updated to the focused element, the `focusin` event won't fire, until the window gets focused back (clicking inside it).
I guess that's an expected browser-UX feature, where the browser waits for the user to actually focus the element (thus focus the browser window first) …
=> Fix focusin-based tests

www/content/docs.md
Two trivial fixes found while reading the docs:
* Add a missing `'`, courtesy of the [Apostrophe Protection Society](https://www.apostrophe.org.uk/) :-). It's an abbreviation of "let us" here, not the word "lets".
* Remove a duplicated word "event".
=> Trivial grammar fixes

www/content/attributes/hx-swap-oob.md
SVGs have issues when you try and modify their contents because they have a different namespace that is only setup when you wrap them in a svg tag.  So to allow internal SVG replacment I've found you can use wrapping in both template and svg tags which then works well with OOB swaps.  It is also possible to do similar full swaps but you have to use hx-select and its not as easy.
Performed manual testing of different oob internal svg swaps to check it works as expected
=> Documentation of svg oob swaps

test/attributes/hx-vals.js, www/content/attributes/hx-vals.md
This PR improves the documentation for `hx-vals` to indicate a potentially useful usage.
Corresponding issue: https://github.com/bigskysoftware/htmx/issues/2885
A test is added for this usage.
=> Documentation for dynamic hx-vals

www/content/docs.md, www/content/headers/hx-location.md, www/content/headers/hx-push-url.md, www/content/headers/hx-redirect.md, www/content/headers/hx-replace-url.md, www/content/headers/hx-trigger.md, www/content/reference.md
Added some documentation for how response headers are not received or processed when 3xx response codes are returned.
#2879 
=> Documentation 3xx redirects can't send headers

www/content/attributes/hx-swap-oob.md
This extends the `hx-swap-oob` documentation with more information on using it with alternate swap strategies which can be finicky, all my conclusions are based on trial and error using htmx 2.0.2 on Firefox 129.
More background on all the testing I did can be found in #2560 
* ~~[ ] I ran the test suite locally (`npm run test`) and verified that it succeeded~~
=> [Documentartion]Add more information about other swap strategies

www/content/reference.md
Hello. :wave: This is missing from the reference page but properly documented on the events page. This simply links the two together so anyone can quickly jump between the two.
Corresponding issue: N/A. I ended up fixing this outright instead of logging an issue.
I couldn't find a corresponding unit test for this change so visually verified by running `zola serve` locally. Here's a quick screencast that demonstrates the change works:
https://github.com/user-attachments/assets/b5b35afb-7a1d-4917-bb32-b75b76007d1b
=> Added htmx before transition reference link

www/content/docs.md
On the docs page, discovery of existing extensions and their documentation is impeded by the lack of an appropriate link.
Although other pages include a link, it makes sense that the docs page also includes it. since it already has an extensions section and so it should not be omitted from there.
=> Add a link to the extensions site on the docs page

src/htmx.js, test/attributes/hx-disabled-elt.js
When we init nodes and find a "load" trigger it does the request straight away and this request may disable some elements with hx-disabled-elt.  However if these disabled elements have not yet had their nodeInit() run yet because they are placed lower in the page then when they later init they first de-init their internalData which removes the requestCount counter used to re-enable them again.  So we need it to handle situations where requestCount is not set and currently it defaults this to -1 and no 0 because of the decrement. So to solve this I've just changed it to fall back to 1 which means that if either requestCount is undefined or if it is equal to 0 it will replace it with 1 and then after the decrement will be 0 and trigger the proper code to enable the element again. …
=> [bug] load trigger stops hx-disabled-elt getting re-enabled

src/htmx.js, test/attributes/hx-trigger.js
Handle any additional whitespace placed at the end of a trigger specification by ignoring it.
#2897 
=> Handle Space before comma in Trigger Spec

src/htmx.js, test/attributes/hx-preserve.js, www/content/attributes/hx-preserve.md
As found in issue #2922, htmx does not process hx-preserve attributes properly when supplied inside a oob-swap response.  Instead the preserved content is just overwritten with the new content from the oob response.
So I've found that simply wrapping the oobSwap() function with handle and restore preserved elements we can indeed support this with just these two lines.  
I also tried with simply moving the handlePreservedElements() funciton up before the oob swap handling code and this in fact does mostly work but it has some bad side effects as when it preserves the element into the fragment it removes the hx-swap-oob tags if done wrong and it can bring oob-swap tags from the page into the fragment which can then act as oob swaps in error.  So to avoid this issue I moved the change to …
=> enable hx-preserve handing for oob swaps

src/htmx.js, test/attributes/hx-trigger.js
Trigger specifications can reference multiple HTML nodes via from and a single element can have multiple trigger specifications for different HTML nodes. One example is given in #2056. Active search with multiple search fields is another one. The latter doesn't currently work because the trigger needs to be on the form element, but the logic doesn't check the event target, but only the element itself.
Corresponding issue: #2056 
Test case covers the original problem from #2056 as well as the related case of referencing different elements. Both tests fail without the implementation change.
=> Change hx-trigger's changed modifier to work for independent trigger specifications

src/htmx.js, test/core/api.js
The htmx.ajax helper function can cause issues when the target is not set correctly or the target selector happens to be missing in the DOM as it passes in null target override to the ajax request which defaults to targeting the body.  Changing it to detect invalid targets and pass in a DUMMY_ELT which triggers the htmx:targetError solves this.  Also had to handle situations where a valid source is supplied as its valid to fall back to source targeting an explicit target is not defined but if we still want it to fail if target was defined.
#2869 
Wrote some new tests to cover most invalid targeting situations and also tested calling htmx.ajax manually to confirm it rejects invalid targets but passes though valid ones fine.
=> fix htmx.ajax defaulting to swap body when target not found

src/htmx.js, test/attributes/hx-select-oob.js
This pull request fixes #2561. I retargeted it against `v1` as suggested on discord. I found this issue with the `hx-select-oob` attribute while trying to help a beginner on discord. This technically breaks an obscure behavior of adding back `#` to a selector if it does not begin with a `#`. This behavior is neither documented nor tested. In fact, the documentation suggests you can use this with any CSS selector, not just id selectors(though it does not give an example). 
> Each value in the comma separated list of values can specify any valid [hx-swap](https://htmx.org/attributes/hx-swap/) strategy by separating the selector and the swap strategy with a :.
As I have explained in the issue, this can cause really strange behavior when combined with non-id selectors by reinterpreting them …
=> Allow non-id selectors in `hx-select-oob` to fix #2561

src/htmx.js, test/manual/hxboost_partial_template_parsing/index.html
Their was a change to add a regex tag utility function in #2024 and this combined three regex creations into a single function.  Since then it seems the svg and title regex were simplified out with the htmx 2.0 re-write and we are now left with a redundant function that is only used to generate a single HEAD_TAG_REGEX which is only used once in makeFragment.  So my proposed change here is to just simply remove this utility function and move the single use regex inline which should simplify readability and code minification.
Previous regex format was:
``` javascript
new RegExp(`<${tag}(\\s[^>]*>|>)([\\s\\S]*?)<\\/${tag}>`, global ? 'gim' : 'im')
```
And I'm simplified this to:
``` javascript
/<head(\s[^>]*)?>.*?<\/head>/is
```
Note [\s\S] is now .* because of the s option and m option is …
=> Optimize Head regex

src/htmx.js, test/attributes/hx-vals.js, test/core/parameters.js
This prevents accessing the `forEach` key on `null` or `undefined` values. `null` is valid in JSON, so it should be supported by the `hx-vals` attribute. This is a regression from 1.x
Could use optional chaining, but I'd imagine that isn't an accepted feature. I also assume the fact it doesn't use `Array.isArray` is because it wants to support other containers that implement `forEach`. So just doing a truthy test is satisfactory, since there is 0% chance that someone is going to be passing `document.all` as a value.
Added test. Change is common sense, but the test ensures it's condition into the future.
=> :bug: Prevents erroring on null vals

src/htmx.js, test/attributes/hx-swap-oob.js
hx-swap-oob attribute is making its way onto the page/dom after ture/outerHTML oob swaps.  They are not needed or used on the page and just add confusion so i've added two lines to remove them from the swapped in content during oobSwap()
#2822 
Wrote a couple of tests to make sure the tags were removed and found one test was broken by my change which I had to update.  Also tested it on my test application to make sure the tags were not seen in the page after swaps.
=> remove extra hx-swap-oob attribute that is not used in the page

src/htmx.js
Bug: 
When `htmx-request` is placed on the same element that is disabled by `hx-disabled-elt` request count is increased twice on the same element. However, when removing request indicators, the request counts for indicators and disabled elements are deducted separately. This meant that when checking the indicators, request count would not be 0, and `htmx-reqest` is not properly removed.
Solution:
Deduct request counts first for both indicators and disabled elements, before removing request indicators.
Corresponding issue: https://github.com/bigskysoftware/htmx/issues/2295 https://github.com/bigskysoftware/htmx/issues/2234
Also in extensions repo: https://github.com/bigskysoftware/htmx-extensions/issues/79
Tested with a personal project as well as using the sample code provided in the …
=> [FIX] Properly remove request indicators

src/htmx.js, test/core/shadowdom.js
In the web component documentation there is a reference to using 'host' to target the web components shadow DOM host element but this was never implemented as a valid target in htmx.  So I've implemented this as a valid selector and added tests to confirm swapping it and elements outside the shadow DOM can be targeted for replacement.
There was a similar 'root' one implemented however from my testing this seems to not be usable for two reasons.  First is that because the shadow root has a very different type called ShadowRoot which does not support most of the options a Node or Element would support which means swaps to this target fail when trying to add classes to the root. Also target has now been wrapped in asElement() which strips root target.  So we should probably remove this non …
=> Add shadowRoot host selector

src/htmx.js
gitlab pipeline seems to be reporting tsc error
```
> htmx.org@2.0.3 types-check
> tsc src/htmx.js --noEmit --checkJs --target es6 --lib dom,dom.iterable
Error: src/htmx.js(586,79): error TS[15](https://github.com/bigskysoftware/htmx/actions/runs/11154764763/job/31004572782#step:5:16)01: This regular expression flag is only available when targeting 'es2018' or later.
Error: Process completed with exit code 2.
```
removing the s from the regex fixes the issue along with updating the regex to not need this flag by having [\s\S] which is all characters including newline which "." does not include unless you add the newer s flag to the regex which is only supported in 2018+ browsers.
Alternative solution is to change package.json type-check line to target es2018 or newer
```json …
```
=> fix es6 tsc checks complaining on newer s regex flag

www/content/attributes/hx-trigger.md
* Clarify the example use of an event filter so that it is clear that you still use the `hx-trigger` attribute and that you use a CSS selector.
Corresponding issue: #2912 
*Viewed the document as rendered markdown.
Two unit tests time out on my machine.
=> Clarify event filter uses in hx-trigger

www/content/essays/htmx-sucks.md, www/content/essays/interviews/henning_koch.md, www/content/essays/is-htmx-another-javascript-framework.md, www/content/essays/rest-explained.md, www/content/extensions/htmx-1-compat.md, www/content/extensions/idiomorph.md, www/content/extensions/sse.md, www/content/headers/hx-trigger.md, www/themes/htmx-theme/highlighting/two-dark-edited.tmTheme
Found a dozen misspellings in docs.
https://github.com/bigskysoftware/htmx/blob/52f8076dcff2b991326713f141a26796c5f5c142/CONTRIBUTING.md?plain=1#L50
https://github.com/crate-ci/typos
=> Fix typos in docs

www/content/server-examples.md
Hi, I included my scala library to the examples section of the website (servers).
I did not run `npm run test`, because it is only a documentation change.
I did run `zola check` that reported a list of broken links, but it didn't include this new one :-).
=> Add htmx4s to scala server-examples

www/content/attributes/hx-trigger.md
I've changed extended CSS selector name from `nearest` to `closest` in the notes section of `hx-trigger` page.
=> Use correct extended CSS selector name in hx-trigger notes section

src/htmx.js, test/attributes/hx-boost.js
I check if the `path` is null or empty when the user hasn't set the action property or has left it empty.
Corresponding issue: #2963
I added two tests that check if everything is OK in two cases (action is unset or is empty)
=> Fix TypeError on null path variable

src/htmx.js, test/core/api.js
recent change #2878 has caused the default behavior of the ajax helper function for when no source or target is supplied to change to error on a target error instead of targeting body as it should do by default.  The recent fix was put in to handle situations where an invalid source or target were supplied which would previously fall back to targeting body in error but the logic for that fix did not handle the case where nothing is supplied for source or target.
#2945 
Added test for when both source and target not set to make sure it targets body as expected
=> ajax helper with no source or target defaults to body

www/content/docs.md
I've added the missing word in the `previous <CSS selector>` documentation.
=> Add missing word in previous CSS selector documentation

www/content/docs.md
Updated link to downlload a copy from unpkg.com to reference correct version 2.0.3
Manually tried the link and it succesfully downloaded version 2.0.3
=> "Download a Copy" in the doc points to old release 2.0.2; this PR changes it to 2.0.3 as it should be

www/content/extensions/_index.md
Typo:
"Serve Sent Events" should be "Server Sent Events" on the [extensions page](https://htmx.org/extensions/)
Previewed in markdown viewer to verify that the table still renders correctly.
=> Fix typo on extensions page

www/content/docs.md
Typo:
"Serve Sent Events" should be "Server Sent Events" on the [docs page](https://htmx.org/docs/)
This is a follow-up to #2983. I believe this section in the docs page was added after the previous pull request was created.
Previewed in markdown viewer
=> docs: Fix typo

www/content/examples/confirm.md
Fixing up a typo in the custom confirmation documentation. 
`evt` is not the correct variable name here - it should be `e`.
Addresses issue #2989 
Tested locally. Worked A-OK
=> Fixing a typo in confirm.md

www/content/essays/_index.md, www/content/essays/a-real-world-nextjs-to-htmx-port.md
Hey, I wrote this essay per our discussion on [Reddit](https://old.reddit.com/r/htmx/comments/1gg2csw/kuttit_open_source_link_shortener_moving_from/lupinr0/). Let me know if you need any changes or additions.
Ran the website locally with Zola.
=> Add Next.js to htmx essay

www/content/extensions/building.md
On the page [Building htmx Extensions](https://htmx.org/extensions/building/) it includes an incomplete list of the extension points available to override. These are `init`, which I can see is used by official htmx extensions, and `getSelectors` which has a test covering its usage.
Coped from source code, which is already covered by tests.
I cross references this with how they're invoked to make sure I wasn't missing any parameters.
=> [Documentation] Add missing default extension points

www/themes/htmx-theme/static/css/site.css, www/themes/htmx-theme/templates/base.html
Without uBlock, the button's alt-text would be 1px lower than the rest
of the nav items, and inconsistently capitalized.
With uBlock, the button would be slightly too high up. Screenshot of problem:
The solution is to apply styles on the `span` that GitHub's JS inserts.
However, using margin will make the entire nav jump during pageload, so
position: relative seems more robust there.
Tested in Firefox and Chrome latest
=> fix vertical alignment of github stars button in all states

www/content/events.md
Correct the `unfilteredParameters` property for the [htmx:configRequest](https://htmx.org/events/#htmx:configRequest) event incorrectly linking to [hx-select](https://htmx.org/attributes/hx-select/) instead of [hx-params](https://htmx.org/attributes/hx-params/).
I have verified that the target page and linked markdown files are as expected.
=> [Documentation] Fix incorrect link

www/content/events.md, www/content/reference.md
The event `htmx:sendAbort` is missing from the documentation. The related events `htmx:sendError` and `htmx:timeout` are there, but this one is missing.
Although `htmx:xhr:abort` is already documented. its detail data is different.
Tested locally using Zola to ensuring linking works correctly.
=> [Documentation] Add missing htmx:sendAbort event

src/htmx.js
Docs for custom extensions show:
https://htmx.org/extensions/building/
> To define an extension you call the htmx.defineExtension() function:
>
> ```html
> <script>
>   htmx.defineExtension('my-ext', {
>     onEvent : function(name, evt) {
>         console.log("Fired event: " + name, evt);
>     }
>   })
> </script>
> ```
> Typically, this is done in a stand-alone javascript file, rather than in an inline script tag.
> ...
> Extensions can override the following default extension points to add or change functionality:
However the current typing doesn't allow this - it requires a fully populated `HtmxExtension` object defining all the methods:
```js
{
init: function(api) {return null;},
getSelectors: function() {return null;},
onEvent : function(name, evt) {return true;}, …
```
=> typing for `defineExtension` should allow partials

src/htmx.js
When trying to handle template tags inside svg tags in a htmx swap it can cause htmx to process the invalid template which is missing its template.content template fragment data causing a swap error.  It seems v2 now scans all templates for oob swap data to handle situations where you need to wrap content in templates but this now causes issues for these invalid templates.
To fix this I've just added a null/undefined check before processing templates in case they have no valid template content data.
#3059 
To test this I've reproduced the problem in the linked issue and made sure this added null check avoids the error message.
=> Handle Invalid template content

src/htmx.js
This fixes an issues in which `bodyContains()` would incorrectly return false for nested shadow roots.
Replaces #2532 
=> Make bodyContains return true for nested shadow roots

src/htmx.js, test/attributes/hx-trigger.js
The `htmx:trigger` event wasn't firing when the trigger was a load.
I added a new test for this scenario, verified that it passes for the fix, and that it doesn't pass without the fix. 
=> Add missing htmx:trigger event on load triggers

src/htmx.js, test/core/api.js
Sometimes, requests that should be only triggered once at load (with `hx-trigger="load"`) are executed twice. This happens for example when calling htmx.process on an existing node (or a parent node) after changing an attribute on the element with `hx-trigger="load"`.
This PR adds a `firstInitCompleted` flag to an element's internalData and adds a check for that flag when handling the `load` triggerEvent.
#2973 
Added a test scenario that changes `hx-swap="afterbegin"` to `hx-swap="beforeend"` on an element with `hx-trigger="load"`, followed by a call to `htmx.process` and checks whether the innerHTML of the element  stayed the same.
This test fails on the dev branch, and passes with this fix.
=> Do not execute hx-trigger="load" on re-initialization of an existing node

src/htmx.js
Inspired by the already merged in extensions [PR #100](https://github.com/bigskysoftware/htmx-extensions/pull/100).
On String, the substr method is deprecated and is not part of the main ECMAScript specification
(see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr).
Replace with the alternatives slice and substring, which are both already used in the codebase.
I made sure that giving bad values caused the existing test cases to fail.
I temporarily added additionally logging to verify that it was doing what I expected.
I checked that most of the changes are trivial so that this could be considered as a single change.
=> Replace deprecated String.prototype.substr usage

src/htmx.js, test/attributes/hx-boost.js, test/attributes/hx-disabled-elt.js, test/attributes/hx-include.js, test/attributes/hx-trigger.js
`hx-include` will include all elements matching the given selector, but currently only supports 1 extended selector at a time, meaning that
```html
<div hx-get="/" hx-include="input, #test">
```
will work, and include values from **all** elements that match any of these 2 selectors.
Using 1 extended selector works well, like
```html
<div hx-get="/" hx-include="find input">
```
will retrieve the first child input's value, and works as expected.
However, the following won't work:
```html
<div hx-get="/" hx-include="find input, previous input">
```
Htmx will currently simply parse the first `find` keyword and use `input, previous input` as the selector to test against previous elements. So, the second part  `previous input` won't work at all, as its `previous` keyword won't even be …
=> Support multiple extended selectors for hx-include, hx-trigger from, and hx-disabled-elt

src/htmx.js, test/core/internals.js
HTMX wasn't cancelling vanilla form submission from buttons with `form` attributes (e.g., outside of `<form>`). 
Corresponding issue: #2919 can probably be closed with this
Added testing in `test/core/internals.js`. After a bit of back and forth on this, Carson agreed that expanding the existing test was appropriate.
=> Cancel vanilla submits from <button[form]/>.

www/content/extensions/preload.md
Pull request should be viewed together with corresponding PR in htmx-extensions repository https://github.com/bigskysoftware/htmx-extensions/pull/106
Added documentation about
- `HX-Preload` header
- form element preloading
- `preload="always"` configuration
=> Update preload extension documentation: form preloading and preload="always"

www/content/examples/active-search.md
Fixes #1569
Fixes #2126
The active search example uses [the chrome-only event "search"](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/search_event) which is not supported in Safari and Firefox. This PR solves that  by using the `keyup[key=='Enter']` trigger. 
I also fixed #2126 so it won't show an empty table on load, it now shows all data initially. I think this better reflects how a real table search would work, but please let me know if you don't agree with that change and I'll remove the `load` trigger.
Corresponding issue: #1569 #2126
Tested on latest the latest version of Firefox and Chromium.
=> Improve active-search example by not using chrome-only event "search"

www/content/examples/file-upload-input.md
I have added a second approach to preserving file inputs after form errors (in the example at *file-upload-input.md*), using `hx-preserve`. 
The approach currently suggested requires a restructuring of the form that will not always be feasible or convenient. I have found that adding `hx-preserve` to the file input 
causes the expected behavior: the user does not have to choose a file again before 
re-submitting the form.
The approach is:
```html
<form method="POST" id="binaryForm" enctype="multipart/form-data" hx-swap="outerHTML" hx-target="#binaryForm">
<input hx-preserve id="someId" type="file" name="binaryFile">
<button type="submit">Submit</button>
</form>
```
I feel this change is necessary because the current version of *file-upload-input.md* 
leaves the impression that there is no …
=> Add reference to hx-preserve to the example at "Preserving File Inputs after Form Errors"

www/content/essays/_index.md, www/content/essays/all/_index.md, www/themes/htmx-theme/templates/essay_all.html, www/themes/htmx-theme/templates/essay_index.html
I set up zola to aggregate all these and create an RSS feed for them. I also removed a couple of the essays from the /essays page in an attempt to highlight the best one for each argument (now that they can all be found on /essays/all).
=> Add /essays/all

www/content/attributes/hx-headers.md
Add an example of evaluated values passed to hx-headers.
I haven't been clear from the documentation how to exactly have the javascript in the attribute evaluated as I'm not such a web dev expert. Perhaps it could help someone else if it's more explicit.
The example is more or less taken from my use case. Please feel free to suggest something else!
HTMX works great with Swift, BTW.
=> Add an example of evaluated values passed to hx-headers.

www/templates/404.html, www/themes/htmx-theme/templates/base.html
Added a 404 page using base template. Users no longer have to manually navigate back to site on 404.
Had to add a check for `current_url` to use the base template as [Zola does not set this variable on 404](https://www.getzola.org/documentation/templates/overview/).
=> Add 404 page

www/content/QUIRKS.md
The docs suggest adding an `htmx-config` with invalid JSON that causes an error when copy/pasting the snippet in.
=> Fix error in quirks documentation for htmx config

www/content/examples/bulk-update.md
This tells the screen reader to announce updates that happen inside the `span#toast` element. Without this, the screen reader does not announce the notification message.
=> Render toast as aria-live region on page load

www/content/events.md
Add descriptions for more properties: `isError`, `serverResponse`, `selectOverride` and `swapOverride`.  
Add a note that modifying values for this event will override how htmx behaves, since this is by design.
Inspected with Zola and verified the links work
=> [Documentation] Make htmx:beforeSwap more complete

www/content/QUIRKS.md
Three documentation links are currently broken on https://htmx.org/quirks/. This patch fixes them.
Corresponding issue: N/A, this is a trivial website change.
=> Fix broken docs links on quirks page

CHANGELOG.md, src/htmx.js, test/core/ajax.js, test/core/internals.js, www/content/docs.md
I would like to start off by thanking @scrhartley for their help with this PR.
When a non-GET htmx request is triggered on an element inside a form, htmx includes the other values in the form. However, it is currently including incorrect values when e.g. a `<button form="referenced">` is inside a different form. This PR addresses that bug. Details are explained in the documentation change and the added test. 
Corresponding issue: None
Using standard HTML behavior as a reference, consider the following:
```
<form id="externalForm" action="/test" method="post">
<input type="text" name="t1" value="textValue">
<input type="hidden" name="b1" value="inputValue">
</form>
<form action="/test2" method="post">
<input type="text" name="t1" value="checkValue">
<button id="submit" form="externalForm" …
```
=> Properly resolve referenced forms.

www/content/events.md
Removed duplicated and incorrect details section from htmx:beforeHistorySave docs
Corresponding issue: N/A
soxurce changes)
=> Fix htmx:beforeHistorySave docs

www/content/essays/alternatives.md
Fixed a broken link URL for TwinSpark in the alternatives essay (duplicate `https://`)
N/A
=> Fixed TwinSpark link in alternatives

www/content/attributes/hx-ext.md
Hi, 
I read the [hx-ext docs](https://github.com/bigskysoftware/htmx/blob/master/www/content/attributes/hx-ext.md) while doing stuff, and I thought it can be made clearer with an example for those who have multiple extensions.
=> Adding example to hx-ext documentation

www/content/essays/10-tips-for-SSR-HDA-apps.md, www/content/essays/a-real-world-nextjs-to-htmx-port.md, www/content/essays/a-real-world-react-to-htmx-port.md, www/content/essays/a-real-world-wasm-to-htmx-port.md, www/content/essays/a-response-to-rich-harris.md, www/content/essays/alternatives.md, www/content/essays/another-real-world-react-to-htmx-port.md, www/themes/htmx-theme/templates/base.html, www/themes/htmx-theme/templates/essay.html
If an essay has a description in the front matter, use that description in the `<meta name="description">` tag.
zola build
=> Allow page description with default if missing

www/content/essays/interviews/_index.md
Adding `_index.md` to the `interviews` folder will mark this folder as a "section". Pages in this section will now inherit section settings from the parent `essays` section, including rendering using the `essay.html` template instead of the default `page.html` template.
Adding `render = false` to the interview section metadata will suppress generating a page at `/essays/interviews/index.html`
=> Mark the interviews folder as a section

www/content/server-examples.md
Adding Free Pascal example of using htmX with Pas2JS
* [ x] I have read the contribution guidelines
* [ x] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
* [ x] This is either a bugfix, a documentation update, or a new feature that has been explicitly
* [ x] I ran the test suite locally (`npm run test`) and verified that it succeeded
=> Add FreePascal server example with Pas2JS

www/content/attributes/hx-headers.md, www/content/docs.md
This Pull Request provides updates to the htmx document regarding the use of the `hx-headers` attribute as part of a CSRF prevention strategy. 
Corresponding issue: #70 (now closed)
Review only
=> Documentation update to include the use of hx-headers to prevent CSRF

www/content/reference.md
I added a missing documentation link to `htmx.org/reference/`, and fixed a typo.
Corresponding issue: n/a
=> Documentation link added

www/content/api.md, www/content/essays/interviews/leonard_richardson.md, www/content/headers/hx-location.md, www/content/headers/hx-push-url.md, www/content/headers/hx-push.md, www/content/headers/hx-redirect.md, www/content/headers/hx-replace-url.md, www/content/headers/hx-trigger.md
=> Add descriptions for /headers/* and /api

www/content/essays/template-fragments.md
Add another library to render blocks in Django templates as fragments (@1cg as discussed on Discord).
=> Add django-block-fragments to template-fragments essay

dist/ext/response-targets.js
> Parameter respCode described in JSDoc does not appear in function signature
Corresponding issue: —
—
=> Fix JSDoc of getRespCodeTarget

www/content/extensions/sse.md
Fix 404 for link to WS extension from SSE extension. Now behaves the same as V1 docs.
Corresponding issue: #3238
=> Fix broken link in SSE extension docs

www/content/attributes/hx-trigger.md
Based upon a discussion in Discord.
Users tend to copy from the docs, so update the `hx-trigger` example to use the `input` event rather than `keyup`, since that will also react to other activity such as via a mouse (e.g. drag to select text, right click and cut). 
=> Documentation update for hx-trigger

www/content/extensions/idiomorph.md
Issue #3205 pointed out that the idiomorph extension documentation fails to mention the extension js file.
Remedy this and update the referenced version while we're at it.
=> Documentation improvements for idiomorph extension

www/content/attributes/hx-select-oob.md
Mention in the docs that the default swap strategy for [`hx-select-oob`](https://htmx.org/attributes/hx-select-oob/) is `outerHTML`.
=> Documentation update for hx-select-oob

www/content/examples/confirm.md
The target is not the element that triggered the request, it does not necessarily have `hx-confirm`.
=> fix customized confirmation example

www/content/attributes/hx-include.md
An addition to the docs mentioning that `hx-include` does not include disabled inputs.
https://github.com/bigskysoftware/htmx/issues/3053
* [+] I have read the contribution guidelines
* [+] I have targeted this PR against the correct branch (`master` for website changes, `dev` for
* [+] This is either a bugfix, a documentation update, or a new feature that has been explicitly
* [+] I ran the test suite locally (`npm run test`) and verified that it succeeded
=> Mention hx-include does not match disabled fields. Fixes #3053

www/content/events.md
Document `event.detail.boosted` for the events `htmx:beforeRequest`, `htmx:beforeSwap` and `htmx:beforeTransition`.
Manually checked that these events do include this property.
=> Documentation update for events

www/content/extensions/_index.md
This link is pointing to a repo I want to change the name of.
Theoretically Github should auto redirect, but I want to fix the link just in case first.
Also I'm switching to linking to npm, that way if I ever need to change it again in the future, I can just update on NPM, and this document doesn't have to update again for me.
=> Docs: Update Link

src/htmx.js, test/core/api.js, test/core/headers.js, test/core/security.js
During loc coverage testing I found an issue where later tests would start to fail if errors happened in previous tests.  This is because on two of the error paths the xhr request lock is not being removed.  So I've added the end lock command to both of these paths.  If a URL is verified and fails verification because it is say blocked because it is cross domain then it will not remove the lock here and any future requests by that same triggering element will fail.  Also if anyhting in the onload response handler throws an error the same thing will happen and the element will be locked out of all future requests.  This bug has probably not been found before because in most situations retrying would just fail again even if you could retry the request.  But this change allows it to fail in …
=> handle removing request lock on errors

src/htmx.js, test/attributes/hx-include.js, test/core/api.js, test/core/parameters.js, test/core/security.js, web-test-runner.config.mjs
This is a follow up to the new web-test-runner testing PR with more fixes to increase code coverage reporting.  
Three new tests written to cover 3 edge cases that had no coverage before
1. calling htmx.process on a non element type triggers an is element check
2. file formData ignores blank file name now tested
3. disabling a sub child element triggers a disabled check in initNode()
When fixing this third one I found the is element disabled checking is used in multiple places without the eltIsDisabled() helper function so fixed this in three places
There was a bug with webkit testing https://github.com/microsoft/playwright/issues/5894 that had a try catch inserted to handle but after much time testing old versions I reproduced the issue again but found it was fixed in 2022 with webkit …
=> Additional Code Coverage

src/htmx.js, test/attributes/hx-push-url.js, test/core/headers.js
To allow loc coverage testing of hard reloads and refreshes I've proxied window.location into htmx.location that is used for .reload() and setting href.  This can then be replaced if needed to allow full testing of the reload features and also this would allow future extensions to override page reloading if required.
Also found instances of document.location usage which should all be just location to minify code.
Added new tests for HX-Refresh and HX-Redirect and history cache miss
=> proxy window.location for testing and extension overrides

src/htmx.js, test/attributes/hx-push-url.js
I've looked at all cases of IE fallbacks that can be removed now that IE 11 is no longer supported by htmx 2.x.
I've included all possible old browser compatibility checks I could find but it may be possible to roll back some of these changes
As well as just safely removing dead un-needed fallbacks I also found three bugs that the removals have also forced me to address
1st is NormalizePath() which does not function at all as calling new URL(path) without an origin domain added as a second parameter is designed to throw errors every time causing the IE11 fallback to happen for ALL calls to normalizePath and this fallback does zero normalization.  I don't think this lost functionality would have caused big issues as this function is only used to set and restore paths to history so even if …
=> Remove old IE support

src/htmx.js, test/util/util.js
Follow up to #2951.
Replace more usages of deprecated `String.prototype.substr`.
Should I just keep making these, or perhaps we could make this a lint check or something?
Trivial change
=> Get rid of latest usages of substr

src/htmx.js
Changing the title update to use `innerText` instead of `innerHTML` calms some security checks such as GitHub's own code checking.
`tsc` is grumpy now though with the error `Property 'innerText' does not exist on type 'Element'.`
Not sure if i agree with `tsc` fully.
=> Write title as innerText instead of innerHTML

src/htmx.js, test/attributes/hx-vals.js
When using `hx-vals` (and `hx-vars`) you can reference `event` as shown in the docs for [`hx-vals`](https://htmx.org/attributes/hx-vals/).
However when a delay modifier is used in `hx-trigger` this stops being true, since it's actually a reference to [window.event](https://developer.mozilla.org/en-US/docs/Web/API/Window/event), rather than an argument being passed. This is surprising and also its documentation says:
> Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the [compatibility …
=> Fix event not being available in hx-vals/hx-vars when hx-trigger has delay

package.json
Follow up to #2951 and #3074.
At the time of writing, all usages of the deprecated `String.prototype.substr` have been removed from htmx.
Add a lint rule to prevent it being reintroduced in the future.
Manually checked succeeding and failing with the new rule
=> Add substr lint

www/content/examples/confirm.md
Update `htmx:confirm` example to take inheritance into account when checking for `hx-confirm` usage.
Corresponding issue: #3242
=> Correction for confirm example

src/htmx.js
The typescript type claims that the `event` parameter for `HtmxExtension.onEvent` can take `Event|CustomEvent`, but that's not true it can only ever receive a `CustomEvent`. Fix this since it's not a requirement for extensions to deal with an `Event` and the definition of that type doesn't have a `detail` property.
Ran `npm run types-check`, the dist script and `npm run types-generate` to verify the type is now correct.
=> Fix type for event parameter

package-lock.json, package.json, web-test-runner.config.mjs
Just a minor devops tests fixup.  The @web/test-runner had an issue with one of the reporters I had to workaround to retain proper error reporting.  My PR https://github.com/modernweb-dev/web/pull/2932 to fix it just merged upstream so now able to update and remove my temporary workaround.
Re-ran the test via cli and browser with no issues.  Errors and logs are showing as expected
=> update web test-runner and remove temp summaryReporter workaournd

src/htmx.js
Even though it's in the docs for  [`htmx:beforeSwap`](https://htmx.org/events/#htmx:beforeSwap) and the event relies on it, the property `detail.requestConfig.elt` is missing from the TypeScript definition of HtmxRequestConfig.
Looking at the code it's not obvious where it's coming from:
after `requestConfig` is defined, `triggerEvent` is immediately called which adds `elt` to the passed in object.
Fix the type definition and explicitly add `elt` to the `requestConfig` definition to lessen the confusion.
Ran dist to make sure the type turned up in the generated .d.ts file.
=> Fix missing TypeScript property

src/htmx.js, test/attributes/hx-swap-oob.js
This change alters how the oobSwap function builds the query selector string.  Problem is usage of raw_id value obtained from getRawAttribute(oobElement, "id") without escaping.
> Original PR by https://github.com/FraserChapman is here: https://github.com/bigskysoftware/htmx/pull/2319 but there is no activity, so I decided to take over.
This fix allows the call querySelectorAll to return the nodelist of all elements with the ids such as "foo-/bar" - without getting "Failed to execute 'querySelectorAll' on 'Document': '#foo-/bar' is not a valid selector, and whilst not limiting the selection to the first matching id in the document.
https://github.com/bigskysoftware/htmx/issues/1537
I ran the htmx.js test suite Version: 2.0.4 and got 0 failures
I also manually tested …
=> Fixes issue 1537 - OOB does not escape query selector - updated version

src/htmx.js
`extensionsToIgnore` has been added to `withExtensions` which allows developers to filter the extensions within the internal api. 
https://github.com/bigskysoftware/htmx-extensions/issues/145
I've manually tested it by creating an extension `merge-vals` that modifies the parameters through `encodeParameters`, while being used at the same time with `json-enc-custom` like so
```
...
hx-ext="merge-vals,json-enc-custom"
...
```
the extension implementation:
```js
encodeParameters: function(xhr, parameters, elt) {
xhr.overrideMimeType("text/json");
let mergedVals = api.mergeObjects({}, parameters);
if …
```
=> Feature: add extensionsToIgnore to withExtensions

src/htmx.js
In `addEventListener`, when the `triggerSpec.changed` if block was entered, `node` was being set to `event.target`. This technically works, but is deprecated and should use `evt.target` instead like the rest of `addEventListener`.
Corresponding issue: https://github.com/bigskysoftware/htmx/issues/3179
Smoke test a basic changed trigger flow. `/hello` should get called as expected (meaning that `node`, and thus `node.value` are still getting assigned as expected):
```
<select id="select">
<option>1</option>
<option>2</option>
</select>
<div hx-get="/hello" hx-trigger="click changed from:#select"></div>
```
=> Typo in addEventListener - use evt instead of event

src/htmx.js, test/core/events.js
When `hx-target` is inherited, currently the value of `event.detail.target` for `htmx:targetError` is null.
This value should instead be the value that htmx was using to try to resolve the target.
Added a test for the event when inheritance is not being used, since that seemed to not exist yet.
Then added a test which uses an inherited value for `hx-target`.
(I also manually tested that the event doesn't fire when the inherited target does exist.)
=> Fix target value in htmx:targetError when inheritance has been used

src/htmx.js, test/attributes/hx-include.js, test/attributes/hx-indicator.js
This addresses #1754 
This change allows inheriting parent `hx-include` / `hx-indicator` values and expanding on them, such as:
```html
<div hx-include="#someInput">
<div hx-include="inherit, .some-class">
<button hx-include="inherit, #anotherThing" hx-post="/url"></button>
</div>
</div>
```
Which would result in the button's request including `#someInput`, `.some-class` as well as `#anotherThing`
=> Inherit list-keyword in hx-include / hx-indicator

README.md, package.json
Follow-up to #3052 , when we moved the ws/sse test suite to the extensions repo, we forgot some obsolete links/mentions behind
=> Remove obsolete npm command + fix links to ws/sse extensions

test/attributes/hx-swap.js, test/core/api.js
found `npm run test:all` to perform multi browser tests now has an issue with view transition tests in firefox testing and the timeout of 30ms is too low sometimes in other browsers
Updated timeout and wrapped the tests so they only run in chrome where view transitions work as expected.
ran `npm run test:all` to verify multi browser tests still work well
=> Fix non chrome view transtions tests

src/htmx.js, test/attributes/hx-vals.js, www/content/attributes/hx-vals.md
This is a replacement to PR #3139 since its merge conflicts haven't been fixed after a month.
Example:
```html
<div hx-post="/vars" hx-vals="javascript:{ ...this.dataset }" data-name="a name" data-hello="world"></div>
```
We want it to evaluate to `{ "name": "a name", "hello": "world" }` where `this` refers to the div with the hx-vals attribute.
_Note:
The PR makes `this` refer to the `hx-vals` element, rather than the triggering element, and is hence similar to the behavior of `this` when used with [`hx-on`](https://htmx.org/attributes/hx-on/), [`hx-target`](https://htmx.org/attributes/hx-target/) and [`hx-sync`](https://htmx.org/attributes/hx-sync/)._
Corresponding issue: None. _(Although it was mentioned as #1103 in PR #3139, the original problem described there doesn't correspond with …
=> Allow use of "this" when evaluating hx-vals

src/htmx.js, test/core/internals.js, test/core/regressions.js
A recent change #3336 that just shipped in 2.0.5 has introduced a regression bug where if links contain elements trigger click events it now uses the contained element instead of the wrapping link to make the decision of if the click should prevent a links default navigation behavior.  The fix that broke it was designed to handle situations where you listen for a click event on a higher up element causes checkboxes and other elements to lose their ability to operate with clicks if the active htmx element is a form or a link. And to fix this issue it now checks the element that was clicked for if it is a link to prevent instead of the active htmx element.
To fix this issue i've added a line to the shouldCancel link checking code to located the closest wrapping link (or the event element …
=> fix click events on elements wrapped by link don't cancel link navigation

TESTING.md, editors/jetbrains/htmx.web-types.json, test/attributes/hx-swap-oob.js, www/content/_index.md, www/content/events.md, www/static/test/attributes/hx-swap-oob.js
Some variables names were misspelled.
=> Fix variable names

src/htmx.js, www/content/attributes/hx-indicator.md
Updating indicator inline style tag so that it uses visibility:hidden as well as opacity so that screen readers will not announce the invisible indicators to users to improve default accessibility
Note I found the current indicator only does a fade in when it shows and does a instant vanish after the request which has been this way for 2 years since a bug was fixed to prevent the indicators fade out showing briefly on hx-location page loads.  I kept the same behavior but just added visibility.
Also I found there was a lot of wasted white space being added in the old code which impacted minification so resolved this and optimized the duplicate class config variable use with const's.
Also updated the hx-indicator documentation to match the new default style and improved the documentation …
=> update indicator style to have visibility:hidden for screen readers

www/content/examples/modal-custom.md, www/content/examples/modal-uikit.md, www/content/examples/tabs-javascript.md
The custom model example [page](https://htmx.org/examples/modal-custom/) has script tags for htmx and hyperscript in both the head and the body. Remove the redundant tags from the body.
Additionally removed extra hyperscript script tags from the UIKit example [page](https://htmx.org/examples/modal-uikit/) and the JavaScript tabs example [page](https://htmx.org/examples/tabs-javascript/). For the former this actually fixes a problem with its behavior.
I checked the examples still worked when running locally using Zola.
=> Remove redundant script tags

src/htmx.js, test/core/validation.js, www/content/api.md, www/content/docs.md, www/content/events.md, www/content/reference.md
Adds support for reportValidity instead of just using checkValidity like it currently does.  Because this could possible alter existing applications that don't expect their htmx activated forms to report invalid inputs and update the focus to the first invalid input currently in htmx i've put it behind a new config item.  This is default browser behaviour so all users should ideally have this config turned on but having it has a config will prevent any change to existing applications while allowing users than want this the option to turn it on.
Also this change also allows disabling the report validity if you use preventDefault in the htmx:validation:failed event.
Also had to ensure that reportValidity only fires on the first invalid input so it focuses the right item.
This could replace …
=> implement reportValidity for reporting proper form validation errors behind config flag

test/core/api.js
ajax api test for body was causing problems possibly as it was swapping and then reverting body.  Change this test so it just checks if the body is the target but uses a swap of none so it won't possibly cause issues to the body state.
Ran tests locally to make sure they still pass.
=> Fix ajax api body test

www/content/docs.md
Recommend using a form with a hidden input or an adjacent CSRF token in the header. Stop recommending a global token in the `html` or `body` tags as those may not work with `hx-boost`.
Fix #3379
=> Update CSRF recommendation

www/content/attributes/hx-swap-oob.md
Typo: excapsulate -> encapsulate
=> Update hx-swap-oob.md typo: excapsulate -> encapsulate, Fixed #3406

www/content/docs.md
This PR fixes two minor issues in the documentation:
Double negation typo
Original: hx-boost does not not update the <html> or <body> tags...
Fixed: hx-boost does not update the <html> or <body> tags...
Explanation: Removed a duplicated "not".
Grammar and consistency in terminology
Original: The MDN Article provide a good jumping off point...
Fixed: The MDN Article provides a good jumping-off point...
Explanation:
Corrected subject-verb agreement (article → provides).
Added hyphens in "jumping-off point" as a compound adjective.
=> Fix minor typos and grammar in documentation
